# UpdateDB.ini
# C:\Users\<user>\AppData\Local\WP-Plan
# Bei einem SW-Update wird UpdateDB.ini und die aktuelle DB in das user AppData Verzeichnis kopiert.
# Im Installationsverzeichnis ist durch den SW-Update die neue geänderte DB.
# Die ini Datei mit den Scripten wird von der Anwendung geladen und ausgeführt.
# Damit hat die aktuelle gesicherte DB die geänderte Struktur bei einer ev. Änderung.
# Anschließend erfolgt der Datenimport aus der gesicherten DB.
# 
# Beispiele:
#SQL1=CREATE TABLE ThisTable(ID INT, Name CHAR)
#SQL1=ALTER TABLE ThisTable ADD COLUMN Salary CHAR
#SQL2=ALTER TABLE ThisTable ADD COLUMN Nummer CHAR
#
#SQL1=ALTER TABLE ThisTable ALTER COLUMN Salary INT
#SQL2=ALTER TABLE ThisTable ALTER COLUMN Nummer CHAR
#
#
#
# SQL Scripte zur Tabellenänderung:
[TABELLEN]
ANZAHL=1
SQL1=CREATE TABLE Tab_PV(ID INT,Name CHAR,Beschreibung CHAR,Leistung DOUBLE,Wirkungsgrad DOUBLE,U_Mpp DOUBLE,U_Leerlauf DOUBLE,I_Mpp DOUBLE,I_Kurzschluss DOUBLE,Temp_Koeffizient DOUBLE,Laenge DOUBLE,Breite DOUBLE)

[SPALTEN]
ANZAHL=0

[DATENTYPEN]
ANZAHL=0

[IMPORT]
ANZAHL=37
TAB1=Tab_Einstellungen
TAB2=Tab_Solar
TAB3=DB-Heizung
TAB4=DBGebaeude
TAB5=DBTagV
TAB6=DBTagVDaten
TAB7=Tab_Klimaregion
TAB8=Tab_Klimadaten
TAB9=Tab_Projekt
TAB10=Tab_Applikation
TAB11=Tab_BHKW
TAB12=Tab_Typ_Energieanlagen
TAB13=Tab_WP
TAB14=Tab_Kenndaten
TAB15=Tab_Kenndaten_Kuehlung
TAB16=Tab_Prozesstyp
TAB17=Tab_Prozesswaerme
TAB18=Tab_Simulation_Ergebnis
TAB19=Tab_Solarganglinie
TAB20=Tab_SolarganglinieDaten
TAB21=Tab_Solarkollektoren
TAB22=Tab_Stromganglinie
TAB23=Tab_StromganglinieDaten
TAB24=Tab_Stromspeicher
TAB25=Tab_Stromverbrauchertyp
TAB26=Tab_Stromverbraucher
TAB27=Tab_Waermebedarf
TAB28=Tab_WaermebedarfDaten
TAB29=Tab_PV
TAB30=Tab_Energieanlagen
TAB31=Z_Projekt_Stromverbraucher
TAB32=Z_ProjektGebaeude
TAB33=Z_ProjektSolarganglinie
TAB34=Z_ProjektSolarkollektoren
TAB35=Z_ProjektStromganglinie
TAB36=Z_ProjektWaermebedarf
TAB37=Z_Projekt_Prozesswaerme

[DELETE]
ANZAHL=23
TAB1=Tab_Projekt
TAB2=Tab_Prozesswaerme
TAB3=Tab_Prozesstyp
TAB4=Tab_Klimaregion
TAB5=Tab_Applikation
TAB6=Tab_Einstellungen
TAB7=Tab_Kenndaten
TAB8=DBTagV
TAB9=Tab_WP
TAB10=Tab_BHKW
TAB11=Tab_Waermebedarf
TAB12=Tab_Typ_Energieanlagen
TAB13=Tab_Simulation_Ergebnis
TAB14=Tab_Solar
TAB15=Tab_Solarganglinie
TAB16=Tab_Solarkollektoren
TAB17=DBGebaeude
TAB18=DB-Heizung
TAB19=Tab_Stromganglinie
TAB20=Tab_Stromspeicher
TAB21=Tab_Stromverbraucher
TAB22=Tab_Stromverbrauchertyp
TAB23=Tab_PV