"""Recalculate the synthetic Multi Use example with the saved GUI parameters.

This explicitly uses perfect future information (--oracle). For real site data
or a different strategy, use the full command generated by the parameter editor.
"""
from datetime import datetime
from pathlib import Path
import argparse
import json
import webbrowser

from run import run
from visualize_results import ROOT, build


def recalculate(open_browser=False):
    config_path = ROOT / 'config_gui.json'
    if not config_path.is_file():
        raise ValueError('Zuerst die geaenderten Eingaben als config_gui.json im Ordner Speichersimulation speichern.')
    config = json.loads(config_path.read_text(encoding='utf-8-sig'))
    print(f"Neuberechnung: Multi Use, synthetische Beispieldaten, perfekte Zukunftsinformation.")
    print(f"Konfiguration: {config_path}")
    print(f"Peak-Ziel: {config['control']['peak_target_kw']} kW")
    result_dir = ROOT / 'ergebnisse' / ('gui_' + datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
    summary = run(ROOT / 'beispieldaten' / 'synthetisch_3_tage.csv', config_path,
                  'multi_use', result_dir, oracle=True)
    output = ROOT / 'Auswertung.html'
    build(config_path, [(ROOT / 'ergebnisse', 'Eigene Läufe'),
                        (ROOT / 'beispielergebnisse', 'Mitgelieferte Beispiele')], output)
    if open_browser:
        webbrowser.open(output.as_uri())
    return result_dir, summary


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--open', action='store_true')
    args = parser.parse_args()
    try:
        folder, summary = recalculate(args.open)
        print(f'Ergebnis gespeichert: {folder}')
        print(f'Grafik aktualisiert: {ROOT / "Auswertung.html"}')
    except (ValueError, OSError) as error:
        parser.exit(1, str(error) + '\n')
