//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.MyResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.MyResource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ausgewählt.
        /// </summary>
        public static string Text_Ausgewaehlt {
            get {
                return ResourceManager.GetString("Text_Ausgewaehlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        public static string Text_Beschreibung {
            get {
                return ResourceManager.GetString("Text_Beschreibung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte zuerst ein Projekt auswählen!.
        /// </summary>
        public static string Text_Form_Start_MessageBox1 {
            get {
                return ResourceManager.GetString("Text_Form_Start_MessageBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt öffnen oder zuletzt geöffnet.
        /// </summary>
        public static string Text_Form_Start_MessageBox2 {
            get {
                return ResourceManager.GetString("Text_Form_Start_MessageBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geöffnet.
        /// </summary>
        public static string Text_Geoeffnet {
            get {
                return ResourceManager.GetString("Text_Geoeffnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinweis.
        /// </summary>
        public static string Text_Hinweis {
            get {
                return ResourceManager.GetString("Text_Hinweis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Text_Name {
            get {
                return ResourceManager.GetString("Text_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nicht geöffnet.
        /// </summary>
        public static string Text_nicht_geoffnet {
            get {
                return ResourceManager.GetString("Text_nicht_geoffnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt.
        /// </summary>
        public static string Text_Projekt {
            get {
                return ResourceManager.GetString("Text_Projekt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bitte auswählen!.
        /// </summary>
        public static string Text_Select {
            get {
                return ResourceManager.GetString("Text_Select", resourceCulture);
            }
        }
    }
}
