-- 001_grundschema.sql - EPOS-Plan, Zielschema SQLite (Arbeitspaket S2)
-- Erzeugt von sql/tools/Erzeuge-Schema.ps1, Quellenstand 2026-09-01 15:16
-- Quelle: C:\ProgramData\EPOS_PLAN\Kenndaten.accdb (Schemastand 61, nach S0)
-- NICHT VON HAND AENDERN - neu erzeugen. Ab S4-Beginn eingefroren.
--
-- Alle Tabellen sind STRICT. Die FREMDSCHLUESSEL stehen hier und nicht in 003,
-- weil SQLite sie nach dem CREATE TABLE nicht nachruesten kann.
-- PRAGMA foreign_keys = ON ist Pflicht je Verbindung, sonst sind sie wirkungslos.
--
-- Reihenfolge beim Aufbau: 001 -> 002 -> 003.

PRAGMA foreign_keys = OFF;

CREATE TABLE "Berichtskonfiguration" (
    "ID" INTEGER PRIMARY KEY,
    "ProjektID" INTEGER,
    "KonfigJson" TEXT,
    "GeaendertAm" TEXT
) STRICT;

CREATE TABLE "emissionsart" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "kuerzel" TEXT CHECK (length("kuerzel") <= 30),
    "name" TEXT CHECK (length("name") <= 100),
    "einheit" TEXT CHECK (length("einheit") <= 20),
    "co2_aequivalent" REAL,
    "aequivalent_quelle" TEXT CHECK (length("aequivalent_quelle") <= 120),
    "ist_pflicht" INTEGER NOT NULL DEFAULT 0 CHECK ("ist_pflicht" IN (0,1)),
    "ausgewaehlt" INTEGER NOT NULL DEFAULT 0 CHECK ("ausgewaehlt" IN (0,1)),
    "ist_auslieferung" INTEGER NOT NULL DEFAULT 0 CHECK ("ist_auslieferung" IN (0,1)),
    "sortierung" INTEGER
) STRICT;

CREATE TABLE "emissionswert" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "emissionsart_id" INTEGER NOT NULL,
    "carrier_id" INTEGER,
    "quelle" TEXT CHECK (length("quelle") <= 30),
    "quelle_text" TEXT,
    "wert" REAL,
    "ist_co2e" INTEGER NOT NULL DEFAULT 0 CHECK ("ist_co2e" IN (0,1)),
    "ist_aktiv" INTEGER NOT NULL DEFAULT 0 CHECK ("ist_aktiv" IN (0,1)),
    "herkunft_id" INTEGER,
    "ist_auslieferung" INTEGER NOT NULL DEFAULT 0 CHECK ("ist_auslieferung" IN (0,1)),
    "gueltig_ab" TEXT,
    FOREIGN KEY ("emissionsart_id") REFERENCES "emissionsart" ("id")
) STRICT;

CREATE TABLE "energy_carrier" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Brennstoff" INTEGER DEFAULT 0,
    "name" TEXT CHECK (length("name") <= 64),
    "code" TEXT CHECK (length("code") <= 32),
    "group_code" TEXT CHECK (length("group_code") <= 32),
    "pricing_model" TEXT CHECK (length("pricing_model") <= 32),
    "billing_unit" TEXT CHECK (length("billing_unit") <= 16),
    "hi_kwh_per_unit" REAL,
    "hs_kwh_per_unit" REAL,
    "price_work" REAL DEFAULT 0,
    "price_base" REAL DEFAULT 0,
    "price_power" REAL DEFAULT 0,
    "co2" REAL DEFAULT 0,
    "so2" REAL DEFAULT 0,
    "nox" REAL DEFAULT 0,
    "density" REAL,
    "is_active" INTEGER NOT NULL DEFAULT 0 CHECK ("is_active" IN (0,1)),
    "sort_order" INTEGER,
    "price_power_modus" TEXT CHECK (length("price_power_modus") <= 10)
) STRICT;

CREATE TABLE "energy_conversion" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "id_brennstoff" INTEGER,
    "from_unit" TEXT CHECK (length("from_unit") <= 16),
    "to_unit" TEXT CHECK (length("to_unit") <= 16),
    "factor" REAL NOT NULL,
    "user_edited" INTEGER NOT NULL DEFAULT 0 CHECK ("user_edited" IN (0,1)),
    "faktor_name" TEXT CHECK (length("faktor_name") <= 50),
    "aktiv" INTEGER NOT NULL DEFAULT 0 CHECK ("aktiv" IN (0,1)),
    FOREIGN KEY ("id_brennstoff") REFERENCES "Tab_Brennstoff_Stamm" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "energy_price" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Projekt" INTEGER NOT NULL DEFAULT 0,
    "carrier_id" INTEGER NOT NULL,
    "valid_from" TEXT NOT NULL,
    "valid_to" TEXT,
    "grundpreis" REAL,
    "arbeitspreis" REAL NOT NULL,
    "arbeitspreis_unit" TEXT CHECK (length("arbeitspreis_unit") <= 16),
    "Heizwert" REAL DEFAULT 0,
    "leistungspreis" REAL,
    "notes" TEXT,
    FOREIGN KEY ("carrier_id") REFERENCES "energy_carrier" ("id") ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY ("ID_Projekt") REFERENCES "Tab_Projekt" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "energy_project_settings" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Projekt" INTEGER NOT NULL DEFAULT 0,
    "ID_Energieträger" INTEGER DEFAULT 0,
    "ID_Umrechnung" INTEGER DEFAULT 0,
    "custom_hi" REAL DEFAULT 0,
    "custom_hs" REAL DEFAULT 0,
    "custom_price_work" REAL DEFAULT 0,
    "custom_price_base" REAL DEFAULT 0,
    "custom_price_power" REAL DEFAULT 0,
    "co2" REAL DEFAULT 0,
    "so2" REAL DEFAULT 0,
    "nox" REAL DEFAULT 0,
    "Aufschlag_Netzentgelt" REAL,
    "Aufschlag_Netzentgelt_Aktiv" INTEGER NOT NULL DEFAULT 0 CHECK ("Aufschlag_Netzentgelt_Aktiv" IN (0,1)),
    "Aufschlag_Umlagen" REAL,
    "Aufschlag_Umlagen_Aktiv" INTEGER NOT NULL DEFAULT 0 CHECK ("Aufschlag_Umlagen_Aktiv" IN (0,1)),
    "Aufschlag_Stromsteuer" REAL,
    "Aufschlag_Stromsteuer_Aktiv" INTEGER NOT NULL DEFAULT 0 CHECK ("Aufschlag_Stromsteuer_Aktiv" IN (0,1)),
    "Aufschlag_Konzession" REAL,
    "Aufschlag_Konzession_Aktiv" INTEGER NOT NULL DEFAULT 0 CHECK ("Aufschlag_Konzession_Aktiv" IN (0,1)),
    "Aufschlag_Vertrieb" REAL,
    "Aufschlag_Vertrieb_Aktiv" INTEGER NOT NULL DEFAULT 0 CHECK ("Aufschlag_Vertrieb_Aktiv" IN (0,1)),
    "Aufschlag_Modus" TEXT CHECK (length("Aufschlag_Modus") <= 50),
    "Aufschlag_Override" REAL,
    "Verguetung_PV" REAL,
    "Verguetung_BHKW" REAL,
    "Anteil_Energiesteuer" REAL,
    "Anteil_Energiesteuer_Aktiv" INTEGER NOT NULL DEFAULT 0 CHECK ("Anteil_Energiesteuer_Aktiv" IN (0,1)),
    "Anteil_CO2" REAL,
    "Anteil_CO2_Aktiv" INTEGER NOT NULL DEFAULT 0 CHECK ("Anteil_CO2_Aktiv" IN (0,1)),
    "Anteil_Netzentgelt" REAL,
    "Anteil_Netzentgelt_Aktiv" INTEGER NOT NULL DEFAULT 0 CHECK ("Anteil_Netzentgelt_Aktiv" IN (0,1)),
    "Anteil_Vertrieb" REAL,
    "Anteil_Vertrieb_Aktiv" INTEGER NOT NULL DEFAULT 0 CHECK ("Anteil_Vertrieb_Aktiv" IN (0,1)),
    "Anteil_Modus" TEXT CHECK (length("Anteil_Modus") <= 20),
    FOREIGN KEY ("ID_Energieträger") REFERENCES "energy_carrier" ("id") ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY ("ID_Projekt") REFERENCES "Tab_Projekt" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "pricing_model" (
    "code" TEXT NOT NULL CHECK (length("code") <= 32),
    "name" TEXT NOT NULL CHECK (length("name") <= 64),
    "has_hi" INTEGER NOT NULL DEFAULT 0 CHECK ("has_hi" IN (0,1)),
    "has_hs" INTEGER NOT NULL DEFAULT 0 CHECK ("has_hs" IN (0,1)),
    "has_powerprice" INTEGER NOT NULL DEFAULT 0 CHECK ("has_powerprice" IN (0,1)),
    "has_density" INTEGER NOT NULL DEFAULT 0 CHECK ("has_density" IN (0,1)),
    PRIMARY KEY ("code")
) STRICT;

CREATE TABLE "Tab_Applikation" (
    "ID" INTEGER NOT NULL,
    "Projektname" TEXT NOT NULL,
    "ID_Projekt" INTEGER,
    "Beschreibung" TEXT,
    "Icon" TEXT,
    "Version_Major" INTEGER,
    "Version_Minor" INTEGER DEFAULT 0,
    "SchemaVersion" INTEGER DEFAULT 0,
    "Emission_Berechnungsmodus" TEXT CHECK (length("Emission_Berechnungsmodus") <= 10),
    PRIMARY KEY ("ID", "Projektname")
) STRICT;

CREATE TABLE "Tab_BHKW" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Projekt" INTEGER,
    "Bezeichner" TEXT NOT NULL,
    "Firma" TEXT,
    "Beschreibung" TEXT,
    "Ptherm" REAL,
    "Pel" REAL,
    "Brennstoff" INTEGER,
    "Wirkungsgrad" REAL,
    "Investition_kwel" REAL,
    "Raumbedarf" REAL,
    "Wartungskosten_kwhel" REAL,
    "Nutzungsdauer" INTEGER,
    "NOX" INTEGER,
    "SO2" INTEGER,
    "CO" INTEGER,
    "CO2" INTEGER,
    "Staub" INTEGER,
    "Motortyp" TEXT,
    "Grenzleistung" REAL,
    "Kosten_Modul" REAL,
    "Kosten_Montage" REAL,
    "Kosten_Lieferung" REAL,
    "Kosten_Schallschutzhaube" REAL,
    "Kosten_Abgasreinigung" REAL,
    "Vorlauf" INTEGER,
    "Ruecklauf" INTEGER
) STRICT;

CREATE TABLE "Tab_BHKW_STAMM" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Bezeichner" TEXT NOT NULL,
    "Firma" TEXT DEFAULT '',
    "Beschreibung" TEXT DEFAULT '',
    "Ptherm" REAL DEFAULT 0,
    "Pel" REAL DEFAULT 0,
    "Brennstoff" INTEGER DEFAULT 0,
    "Wirkungsgrad" REAL DEFAULT 0,
    "Investition_kwel" REAL DEFAULT 0,
    "Raumbedarf" REAL DEFAULT 0,
    "Wartungskosten_kwhel" REAL DEFAULT 0,
    "Nutzungsdauer" INTEGER DEFAULT 0,
    "NOX" INTEGER DEFAULT 0,
    "SO2" INTEGER DEFAULT 0,
    "CO" INTEGER DEFAULT 0,
    "CO2" INTEGER DEFAULT 0,
    "Staub" INTEGER DEFAULT 0,
    "Motortyp" TEXT,
    "Grenzleistung" REAL DEFAULT 0,
    "Kosten_Modul" REAL DEFAULT 0,
    "Kosten_Montage" REAL DEFAULT 0,
    "Kosten_Lieferung" REAL DEFAULT 0,
    "Kosten_Schallschutzhaube" REAL DEFAULT 0,
    "Kosten_Abgasreinigung" REAL DEFAULT 0,
    "Vorlauf" INTEGER DEFAULT 0,
    "Ruecklauf" INTEGER DEFAULT 0,
    "ReadOnly" INTEGER NOT NULL DEFAULT 0 CHECK ("ReadOnly" IN (0,1))
) STRICT;

CREATE TABLE "Tab_Brauchwasser" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Projekt" INTEGER NOT NULL,
    "Bezeichner" TEXT NOT NULL,
    "Typ" TEXT NOT NULL,
    "Beschreibung" TEXT,
    "Monat_1" REAL,
    "Monat_2" REAL,
    "Monat_3" REAL,
    "Monat_4" REAL,
    "Monat_5" REAL,
    "Monat_6" REAL,
    "Monat_7" REAL,
    "Monat_8" REAL,
    "Monat_9" REAL,
    "Monat_10" REAL,
    "Monat_11" REAL,
    "Monat_12" REAL
) STRICT;

CREATE TABLE "Tab_Brauchwasser_STAMM" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Bezeichner" TEXT NOT NULL,
    "Typ" TEXT,
    "Beschreibung" TEXT,
    "Monat_1" REAL,
    "Monat_2" REAL,
    "Monat_3" REAL,
    "Monat_4" REAL,
    "Monat_5" REAL,
    "Monat_6" REAL,
    "Monat_7" REAL,
    "Monat_8" REAL,
    "Monat_9" REAL,
    "Monat_10" REAL,
    "Monat_11" REAL,
    "Monat_12" REAL,
    "ReadOnly" INTEGER NOT NULL DEFAULT 0 CHECK ("ReadOnly" IN (0,1))
) STRICT;

CREATE TABLE "Tab_Brauchwassertyp" (
    "ID" INTEGER NOT NULL DEFAULT 0,
    "ID_Brauchwasser" INTEGER NOT NULL DEFAULT 0,
    "ID_Projekt" INTEGER NOT NULL DEFAULT 0,
    "Typname" TEXT NOT NULL,
    "Beschreibung" TEXT,
    "1" REAL,
    "2" REAL,
    "3" REAL,
    "4" REAL,
    "5" REAL,
    "6" REAL,
    "7" REAL,
    "8" REAL,
    "9" REAL,
    "10" REAL,
    "11" REAL,
    "12" REAL,
    "13" REAL,
    "14" REAL,
    "15" REAL,
    "16" REAL,
    "17" REAL,
    "18" REAL,
    "19" REAL,
    "20" REAL,
    "21" REAL,
    "22" REAL,
    "23" REAL,
    "24" REAL,
    "25" REAL,
    "26" REAL,
    "27" REAL,
    "28" REAL,
    "29" REAL,
    "30" REAL,
    "31" REAL,
    "32" REAL,
    "33" REAL,
    "34" REAL,
    "35" REAL,
    "36" REAL,
    "37" REAL,
    "38" REAL,
    "39" REAL,
    "40" REAL,
    "41" REAL,
    "42" REAL,
    "43" REAL,
    "44" REAL,
    "45" REAL,
    "46" REAL,
    "47" REAL,
    "48" REAL,
    "49" REAL,
    "50" REAL,
    "51" REAL,
    "52" REAL,
    "53" REAL,
    "54" REAL,
    "55" REAL,
    "56" REAL,
    "57" REAL,
    "58" REAL,
    "59" REAL,
    "60" REAL,
    "61" REAL,
    "62" REAL,
    "63" REAL,
    "64" REAL,
    "65" REAL,
    "66" REAL,
    "67" REAL,
    "68" REAL,
    "69" REAL,
    "70" REAL,
    "71" REAL,
    "72" REAL,
    "73" REAL,
    "74" REAL,
    "75" REAL,
    "76" REAL,
    "77" REAL,
    "78" REAL,
    "79" REAL,
    "80" REAL,
    "81" REAL,
    "82" REAL,
    "83" REAL,
    "84" REAL,
    "85" REAL,
    "86" REAL,
    "87" REAL,
    "88" REAL,
    "89" REAL,
    "90" REAL,
    "91" REAL,
    "92" REAL,
    "93" REAL,
    "94" REAL,
    "95" REAL,
    "96" REAL,
    "97" REAL,
    "98" REAL,
    "99" REAL,
    "100" REAL,
    "101" REAL,
    "102" REAL,
    "103" REAL,
    "104" REAL,
    "105" REAL,
    "106" REAL,
    "107" REAL,
    "108" REAL,
    "109" REAL,
    "110" REAL,
    "111" REAL,
    "112" REAL,
    "113" REAL,
    "114" REAL,
    "115" REAL,
    "116" REAL,
    "117" REAL,
    "118" REAL,
    "119" REAL,
    "120" REAL,
    "121" REAL,
    "122" REAL,
    "123" REAL,
    "124" REAL,
    "125" REAL,
    "126" REAL,
    "127" REAL,
    "128" REAL,
    "129" REAL,
    "130" REAL,
    "131" REAL,
    "132" REAL,
    "133" REAL,
    "134" REAL,
    "135" REAL,
    "136" REAL,
    "137" REAL,
    "138" REAL,
    "139" REAL,
    "140" REAL,
    "141" REAL,
    "142" REAL,
    "143" REAL,
    "144" REAL,
    "145" REAL,
    "146" REAL,
    "147" REAL,
    "148" REAL,
    "149" REAL,
    "150" REAL,
    "151" REAL,
    "152" REAL,
    "153" REAL,
    "154" REAL,
    "155" REAL,
    "156" REAL,
    "157" REAL,
    "158" REAL,
    "159" REAL,
    "160" REAL,
    "161" REAL,
    "162" REAL,
    "163" REAL,
    "164" REAL,
    "165" REAL,
    "166" REAL,
    "167" REAL,
    "168" REAL,
    PRIMARY KEY ("ID", "ID_Brauchwasser"),
    FOREIGN KEY ("ID_Brauchwasser") REFERENCES "Tab_Brauchwasser" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_Brauchwassertyp_STAMM" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Bezeichner" TEXT NOT NULL,
    "Beschreibung" TEXT,
    "1" REAL,
    "2" REAL,
    "3" REAL,
    "4" REAL,
    "5" REAL,
    "6" REAL,
    "7" REAL,
    "8" REAL,
    "9" REAL,
    "10" REAL,
    "11" REAL,
    "12" REAL,
    "13" REAL,
    "14" REAL,
    "15" REAL,
    "16" REAL,
    "17" REAL,
    "18" REAL,
    "19" REAL,
    "20" REAL,
    "21" REAL,
    "22" REAL,
    "23" REAL,
    "24" REAL,
    "25" REAL,
    "26" REAL,
    "27" REAL,
    "28" REAL,
    "29" REAL,
    "30" REAL,
    "31" REAL,
    "32" REAL,
    "33" REAL,
    "34" REAL,
    "35" REAL,
    "36" REAL,
    "37" REAL,
    "38" REAL,
    "39" REAL,
    "40" REAL,
    "41" REAL,
    "42" REAL,
    "43" REAL,
    "44" REAL,
    "45" REAL,
    "46" REAL,
    "47" REAL,
    "48" REAL,
    "49" REAL,
    "50" REAL,
    "51" REAL,
    "52" REAL,
    "53" REAL,
    "54" REAL,
    "55" REAL,
    "56" REAL,
    "57" REAL,
    "58" REAL,
    "59" REAL,
    "60" REAL,
    "61" REAL,
    "62" REAL,
    "63" REAL,
    "64" REAL,
    "65" REAL,
    "66" REAL,
    "67" REAL,
    "68" REAL,
    "69" REAL,
    "70" REAL,
    "71" REAL,
    "72" REAL,
    "73" REAL,
    "74" REAL,
    "75" REAL,
    "76" REAL,
    "77" REAL,
    "78" REAL,
    "79" REAL,
    "80" REAL,
    "81" REAL,
    "82" REAL,
    "83" REAL,
    "84" REAL,
    "85" REAL,
    "86" REAL,
    "87" REAL,
    "88" REAL,
    "89" REAL,
    "90" REAL,
    "91" REAL,
    "92" REAL,
    "93" REAL,
    "94" REAL,
    "95" REAL,
    "96" REAL,
    "97" REAL,
    "98" REAL,
    "99" REAL,
    "100" REAL,
    "101" REAL,
    "102" REAL,
    "103" REAL,
    "104" REAL,
    "105" REAL,
    "106" REAL,
    "107" REAL,
    "108" REAL,
    "109" REAL,
    "110" REAL,
    "111" REAL,
    "112" REAL,
    "113" REAL,
    "114" REAL,
    "115" REAL,
    "116" REAL,
    "117" REAL,
    "118" REAL,
    "119" REAL,
    "120" REAL,
    "121" REAL,
    "122" REAL,
    "123" REAL,
    "124" REAL,
    "125" REAL,
    "126" REAL,
    "127" REAL,
    "128" REAL,
    "129" REAL,
    "130" REAL,
    "131" REAL,
    "132" REAL,
    "133" REAL,
    "134" REAL,
    "135" REAL,
    "136" REAL,
    "137" REAL,
    "138" REAL,
    "139" REAL,
    "140" REAL,
    "141" REAL,
    "142" REAL,
    "143" REAL,
    "144" REAL,
    "145" REAL,
    "146" REAL,
    "147" REAL,
    "148" REAL,
    "149" REAL,
    "150" REAL,
    "151" REAL,
    "152" REAL,
    "153" REAL,
    "154" REAL,
    "155" REAL,
    "156" REAL,
    "157" REAL,
    "158" REAL,
    "159" REAL,
    "160" REAL,
    "161" REAL,
    "162" REAL,
    "163" REAL,
    "164" REAL,
    "165" REAL,
    "166" REAL,
    "167" REAL,
    "168" REAL,
    "ReadOnly" INTEGER NOT NULL DEFAULT 0 CHECK ("ReadOnly" IN (0,1))
) STRICT;

CREATE TABLE "Tab_Brennstoff_Stamm" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Kategorie" INTEGER NOT NULL DEFAULT 0,
    "Bezeichner" TEXT NOT NULL,
    "Einheit" TEXT,
    "PreisEinheit" TEXT,
    "Hi" REAL DEFAULT 0,
    "Hs" REAL DEFAULT 0,
    "CO2" REAL DEFAULT 0,
    "SO2" REAL DEFAULT 0,
    "NOx" REAL DEFAULT 0,
    "Staub" REAL DEFAULT 0,
    "PE_Faktor" REAL DEFAULT 0,
    "Standard_Grundpreis" REAL DEFAULT 0,
    "Standard_Arbeitspreis" REAL DEFAULT 0,
    "Standard_Leistungspreis" REAL DEFAULT 0,
    "ReadOnly" INTEGER NOT NULL DEFAULT 0 CHECK ("ReadOnly" IN (0,1)),
    FOREIGN KEY ("ID_Kategorie") REFERENCES "Tab_BrennstoffKategorien" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_BrennstoffKategorien" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Gruppe" TEXT NOT NULL,
    "Code" TEXT
) STRICT;

CREATE TABLE "Tab_DBTagV" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Gebaeude" INTEGER NOT NULL DEFAULT 0,
    "Bezeichner" TEXT NOT NULL,
    "Beschreibung" TEXT,
    FOREIGN KEY ("ID_Gebaeude") REFERENCES "Tab_Gebaeude" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_DBTagV_STAMM" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Bezeichner" TEXT,
    "Beschreibung" TEXT,
    "Veraenderbar" INTEGER NOT NULL DEFAULT 0 CHECK ("Veraenderbar" IN (0,1)),
    "ReadOnly" INTEGER NOT NULL DEFAULT 0 CHECK ("ReadOnly" IN (0,1))
) STRICT;

CREATE TABLE "Tab_DBTagVDaten" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_TagV" INTEGER NOT NULL,
    "Verteilung" REAL,
    FOREIGN KEY ("ID_TagV") REFERENCES "Tab_DBTagV" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_DBTagVDaten_STAMM" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_TagV" INTEGER,
    "Verteilung" REAL,
    "ReadOnly" INTEGER NOT NULL DEFAULT 0 CHECK ("ReadOnly" IN (0,1)),
    FOREIGN KEY ("ID_TagV") REFERENCES "Tab_DBTagV_STAMM" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_Einstellungen" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Projekt" INTEGER NOT NULL DEFAULT 0,
    "BHKW_Grenzleistung" REAL DEFAULT 0,
    "Netzverluste" REAL DEFAULT 0,
    "NetzverlusteEinheit" TEXT DEFAULT '%',
    "WP_Heizstab" INTEGER NOT NULL DEFAULT 0 CHECK ("WP_Heizstab" IN (0,1)),
    "Kessel_Betriebsbereitschaft" INTEGER DEFAULT 0,
    "Tool_1" TEXT,
    "Tool_2" TEXT,
    "Tool_3" TEXT,
    "Tool_4" TEXT,
    "Tool_5" TEXT,
    "Tool_6" TEXT,
    "Ladefuellstand_Min" INTEGER,
    "Ladefuellstand_Max" INTEGER,
    "Ladeleistung_Max" INTEGER,
    "Ladefuellstand_Min_Auswahl" TEXT,
    "Ladefuellstand_Max_Auswahl" TEXT,
    "Ladeleistung_Max_Auswahl" TEXT,
    "Ladeschwellwert" REAL,
    "Betriebsart" INTEGER DEFAULT 0,
    "Leistungsgrenze" INTEGER DEFAULT 0,
    "Pendelspeicher" REAL DEFAULT 0,
    "Extrapolation_erlaubt" INTEGER NOT NULL DEFAULT 0 CHECK ("Extrapolation_erlaubt" IN (0,1)),
    "Kaskade_Zweikanalig" INTEGER NOT NULL DEFAULT 0 CHECK ("Kaskade_Zweikanalig" IN (0,1)),
    "Kanal_Knappheitsreihenfolge" TEXT CHECK (length("Kanal_Knappheitsreihenfolge") <= 100),
    "Booster_Lesepunkt" TEXT CHECK (length("Booster_Lesepunkt") <= 50),
    FOREIGN KEY ("ID_Projekt") REFERENCES "Tab_Projekt" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_Energieanlagen" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Projekt" INTEGER NOT NULL,
    "Bezeichner" TEXT NOT NULL,
    "ID_Type" INTEGER DEFAULT 0,
    "ID_WP" INTEGER DEFAULT 0,
    "Betriebsart" TEXT,
    "Sperrung" INTEGER NOT NULL DEFAULT 0 CHECK ("Sperrung" IN (0,1)),
    "Sperrzeit_von" INTEGER DEFAULT 0,
    "Sperrzeit_bis" INTEGER DEFAULT 0,
    "Vorlauf" INTEGER DEFAULT 0,
    "Rücklauf" INTEGER DEFAULT 0,
    "Bivalenter_Betrieb" INTEGER NOT NULL DEFAULT 0 CHECK ("Bivalenter_Betrieb" IN (0,1)),
    "Abschaltpunkt" REAL DEFAULT 0,
    "Nutzungszeit" INTEGER DEFAULT 0,
    "ID_SP" INTEGER DEFAULT 0,
    "ID_PV" INTEGER DEFAULT 0,
    "ID_Solar" INTEGER DEFAULT 0,
    "Heizstab" INTEGER NOT NULL DEFAULT 0 CHECK ("Heizstab" IN (0,1)),
    "Volumen" REAL DEFAULT 0,
    "rendeMix" INTEGER NOT NULL DEFAULT 0 CHECK ("rendeMix" IN (0,1)),
    "Solaranteil" INTEGER DEFAULT 0,
    "ID_Kessel" INTEGER DEFAULT 0,
    "ID_BHKW" INTEGER DEFAULT 0,
    "Grenzleistung" REAL DEFAULT 50,
    "Kollektormodulanzahl" INTEGER DEFAULT 0,
    "PV_Leistung" REAL DEFAULT 0,
    "Neigung" INTEGER DEFAULT 0,
    "Azimut" INTEGER DEFAULT 0,
    "ID_PUFFER" INTEGER DEFAULT 0,
    "Prioritaet" INTEGER,
    "WQ_Typ" TEXT CHECK (length("WQ_Typ") <= 50),
    "WQ_Temp" REAL,
    "WQ_Monatswerte" TEXT,
    "WQ_CSV" TEXT,
    "WQ_Wochenwerte" TEXT,
    "WQ_Puffer" TEXT,
    "WQ_Spreizung" REAL,
    "WQ_Regeneration" REAL,
    "WQ_Unbegrenzt" INTEGER NOT NULL DEFAULT 0 CHECK ("WQ_Unbegrenzt" IN (0,1)),
    "WS_Typ" TEXT CHECK (length("WS_Typ") <= 50),
    "BM_Typ" TEXT CHECK (length("BM_Typ") <= 50),
    "ID_Carrier" INTEGER DEFAULT 0,
    "WQ_Tiefe" REAL,
    "WQ_Flaeche" REAL,
    "WQ_Anzahl" INTEGER,
    "WQ_Bodentyp" TEXT CHECK (length("WQ_Bodentyp") <= 50),
    "WQ_Quellsystem" TEXT CHECK (length("WQ_Quellsystem") <= 50),
    "WS_Ziel" TEXT CHECK (length("WS_Ziel") <= 50),
    "WS_ID_Puffer" INTEGER,
    "WS_Ladeprio" INTEGER,
    "WS_Ladegrenze" REAL,
    "WS_Ladeprio_PV" INTEGER,
    "WS_Ziel2" TEXT CHECK (length("WS_Ziel2") <= 50),
    "WS_ID_Puffer2" INTEGER,
    "WS_Ladeprio2" INTEGER,
    "WS_Ladegrenze2" REAL,
    "WQ_ID_Puffer" INTEGER,
    "KWKG_Stichtag" TEXT,
    "KWKG_Inbetriebnahme" TEXT,
    "KWKG_Anlagenart" TEXT CHECK (length("KWKG_Anlagenart") <= 24),
    "KWKG_Eigenstromfall" TEXT CHECK (length("KWKG_Eigenstromfall") <= 24),
    "KWKG_Satz_Einspeisung" REAL,
    "KWKG_Satz_Eigen" REAL,
    "KWKG_Vbh_Kontingent" REAL,
    "KWKG_Vbh_Jahresdeckel" REAL,
    "WQ_Anschlusshoehe" REAL,
    "WQ_ID_Quellprofil" INTEGER,
    "WQ_TemperaturModus" TEXT CHECK (length("WQ_TemperaturModus") <= 50),
    "Energiesteuer_Wahl" TEXT CHECK (length("Energiesteuer_Wahl") <= 20),
    "Aufteilung_Methode" TEXT CHECK (length("Aufteilung_Methode") <= 30),
    "Hilfsenergie_Anteil" REAL,
    FOREIGN KEY ("WQ_ID_Quellprofil") REFERENCES "Tab_Quellprofil" ("ID"),
    FOREIGN KEY ("ID_PUFFER") REFERENCES "Tab_Pufferspeicher" ("ID"),
    FOREIGN KEY ("WQ_ID_Puffer") REFERENCES "Tab_Pufferspeicher" ("ID"),
    FOREIGN KEY ("WS_ID_Puffer") REFERENCES "Tab_Pufferspeicher" ("ID"),
    FOREIGN KEY ("WS_ID_Puffer2") REFERENCES "Tab_Pufferspeicher" ("ID"),
    FOREIGN KEY ("ID_BHKW") REFERENCES "Tab_BHKW" ("ID") ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY ("ID_Kessel") REFERENCES "Tab_Heizkessel" ("ID") ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY ("ID_Projekt") REFERENCES "Tab_Projekt" ("ID") ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY ("ID_PV") REFERENCES "Tab_PV" ("ID") ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY ("ID_Solar") REFERENCES "Tab_Solarkollektoren" ("ID") ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY ("ID_SP") REFERENCES "Tab_Stromspeicher" ("ID") ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY ("ID_Type") REFERENCES "Tab_Typ_Energieanlagen" ("ID") ON UPDATE CASCADE,
    FOREIGN KEY ("ID_WP") REFERENCES "Tab_WP" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_Ergebnis" (
    "ID" INTEGER PRIMARY KEY,
    "ID_Projekt" INTEGER,
    "Bezeichner" TEXT,
    "Zeitstempel" TEXT,
    "ID_Klimaregion" INTEGER,
    "Sim_Energiebedarf" INTEGER NOT NULL DEFAULT 0 CHECK ("Sim_Energiebedarf" IN (0,1)),
    "Sim_Waermepumpe" INTEGER NOT NULL DEFAULT 0 CHECK ("Sim_Waermepumpe" IN (0,1)),
    "Sim_Heizkessel" INTEGER NOT NULL DEFAULT 0 CHECK ("Sim_Heizkessel" IN (0,1)),
    "Sim_Solarthermie" INTEGER NOT NULL DEFAULT 0 CHECK ("Sim_Solarthermie" IN (0,1)),
    "Sim_BHKW" INTEGER NOT NULL DEFAULT 0 CHECK ("Sim_BHKW" IN (0,1)),
    "Sim_PV" INTEGER NOT NULL DEFAULT 0 CHECK ("Sim_PV" IN (0,1)),
    "Sim_Stromspeicher" INTEGER NOT NULL DEFAULT 0 CHECK ("Sim_Stromspeicher" IN (0,1))
) STRICT;

CREATE TABLE "Tab_ErgebnisBHKW" (
    "ID" INTEGER PRIMARY KEY,
    "ID_Ergebnis" INTEGER,
    "Waermebedarf" REAL,
    "Restwaermebedarf" REAL,
    "Strombedarf" REAL,
    "Reststrombedarf" REAL,
    "Waermeproduktion" REAL,
    "Waermeueberschuss" REAL,
    "Stromproduktion" REAL,
    "Betriebsstunden_Gesamt" REAL,
    "Betriebsstunden_Durchschnitt" REAL,
    "Waermebedarfsdeckung" REAL,
    "Strombedarfsdeckung" REAL,
    "Gasverbrauch" REAL,
    "Oelverbrauch" REAL,
    "Koks" REAL,
    "Rapsoelverbrauch" REAL,
    "Holzverbrauch" REAL,
    "Kohle" REAL,
    "Sonstigverbrauch" REAL,
    "Pellets" REAL,
    "TierischeFette" REAL,
    "VbhElektrisch" REAL,
    "Deckung_Heizung" REAL,
    "Deckung_Brauchwasser" REAL,
    "Deckung_Prozess" REAL,
    FOREIGN KEY ("ID_Ergebnis") REFERENCES "Tab_Ergebnis" ("ID") ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_ErgebnisBHKWModul" (
    "ID" INTEGER PRIMARY KEY,
    "ID_ErgebnisBHKW" INTEGER,
    "Modul" TEXT,
    "Waermeproduktion" REAL,
    "Stromproduktion" REAL,
    "Brennstoff" TEXT,
    "Verbrauch" REAL DEFAULT 0,
    "carrier_id" INTEGER,
    "VbhThermisch" REAL,
    "VbhElektrisch" REAL,
    "Hilfsenergie" REAL,
    FOREIGN KEY ("ID_ErgebnisBHKW") REFERENCES "Tab_ErgebnisBHKW" ("ID") ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_ErgebnisEnergiebedarf" (
    "ID" INTEGER PRIMARY KEY,
    "ID_Ergebnis" INTEGER,
    "Waermebedarf_Gesamt" REAL,
    "Waermelast_Max" REAL,
    "Strombedarf_Gesamt" REAL,
    "Strombedarf_Max" REAL,
    "Waermerestbedarf" REAL,
    "Stromrestbedarf" REAL,
    "Waermebedarf_Heizung" REAL,
    "Waermebedarf_Brauchwasser" REAL,
    "Waermebedarf_Prozess" REAL,
    FOREIGN KEY ("ID_Ergebnis") REFERENCES "Tab_Ergebnis" ("ID") ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_ErgebnisHeizkessel" (
    "ID" INTEGER PRIMARY KEY,
    "ID_Ergebnis" INTEGER,
    "Waermebedarf" REAL,
    "Restwaermebedarf" REAL,
    "Waermeproduktion" REAL,
    "Strombedarf" REAL,
    "Reststrombedarf" REAL,
    "Waermebedarfsdeckung" REAL,
    "Stromverbrauch" REAL,
    "Maximale_Kesselleistung" REAL,
    "Gasspitze" REAL,
    "Gasverbrauch" REAL,
    "Oelverbrauch" REAL,
    "Koks" REAL,
    "Rapsoelverbrauch" REAL,
    "Holzverbrauch" REAL,
    "Kohle" REAL,
    "Sonstigverbrauch" REAL,
    "Pellets" REAL,
    "TierischeFette" REAL,
    "Quellwaerme" REAL,
    "Deckung_Heizung" REAL,
    "Deckung_Brauchwasser" REAL,
    "Deckung_Prozess" REAL,
    FOREIGN KEY ("ID_Ergebnis") REFERENCES "Tab_Ergebnis" ("ID") ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_ErgebnisHeizkesselModul" (
    "ID" INTEGER PRIMARY KEY,
    "ID_ErgebnisHeizkessel" INTEGER,
    "Modul" TEXT,
    "Waerme_Gas" REAL,
    "Waerme_Oel" REAL,
    "Brennstoff" TEXT,
    "Verbrauch" REAL DEFAULT 0,
    "Jahresnutzungsgrad" REAL,
    "carrier_id" INTEGER,
    "Waermeproduktion" REAL,
    "Hilfsenergie" REAL,
    FOREIGN KEY ("ID_ErgebnisHeizkessel") REFERENCES "Tab_ErgebnisHeizkessel" ("ID") ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_ErgebnisPhotovoltaik" (
    "ID" INTEGER PRIMARY KEY,
    "ID_Ergebnis" INTEGER,
    "Strombedarf" REAL,
    "Reststrombedarf" REAL,
    "Stromproduktion" REAL,
    "Strombedarfsdeckung" REAL,
    "Ueberschuss" REAL,
    "MaxSolareLeistung" REAL,
    FOREIGN KEY ("ID_Ergebnis") REFERENCES "Tab_Ergebnis" ("ID") ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_ErgebnisPhotovoltaikModul" (
    "ID" INTEGER PRIMARY KEY,
    "ID_ErgebnisPhotovoltaik" INTEGER,
    "Modul" TEXT,
    "Flaeche" REAL,
    "Anzahl" INTEGER,
    "Stromproduktion" REAL,
    FOREIGN KEY ("ID_ErgebnisPhotovoltaik") REFERENCES "Tab_ErgebnisPhotovoltaik" ("ID") ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_ErgebnisPufferspeicher" (
    "ID" INTEGER PRIMARY KEY,
    "ID_Ergebnis" INTEGER,
    "ID_Pufferspeicher" INTEGER,
    "Bezeichner" TEXT,
    "Verwendung" TEXT CHECK (length("Verwendung") <= 50),
    "Q_max" REAL,
    "Ladung_gesamt" REAL,
    "Entladung_gesamt" REAL,
    "Verluste_gesamt" REAL,
    "SOC_Ende" REAL,
    "SOC_Mittel" REAL,
    "SOC_Max" REAL,
    "Vollzyklen" REAL,
    "Entladung_Heizung" REAL,
    "Entladung_Brauchwasser" REAL,
    "Entladung_Prozess" REAL,
    "Durchsatz_Geladen" REAL,
    "Durchsatz_Entladen" REAL,
    "ID_Anlage" INTEGER,
    "T_oben_Mittel" REAL,
    "T_oben_Min" REAL,
    FOREIGN KEY ("ID_Ergebnis") REFERENCES "Tab_Ergebnis" ("ID") ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_ErgebnisSolarthermie" (
    "ID" INTEGER PRIMARY KEY,
    "ID_Ergebnis" INTEGER,
    "Waermebedarf" REAL,
    "Restwaermebedarf" REAL,
    "Waermeproduktion" REAL,
    "Waermebedarfsdeckung" REAL,
    "Ueberschuss" REAL,
    "Deckung_Heizung" REAL,
    "Deckung_Brauchwasser" REAL,
    "Deckung_Prozess" REAL,
    FOREIGN KEY ("ID_Ergebnis") REFERENCES "Tab_Ergebnis" ("ID") ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_ErgebnisSolarthermieModul" (
    "ID" INTEGER PRIMARY KEY,
    "ID_ErgebnisSolarthermie" INTEGER,
    "Modul" TEXT,
    "Flaeche" REAL,
    "Anzahl" INTEGER,
    "Waermeproduktion" REAL,
    "Ueberschuss" REAL,
    FOREIGN KEY ("ID_ErgebnisSolarthermie") REFERENCES "Tab_ErgebnisSolarthermie" ("ID") ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_ErgebnisStromMatrix" (
    "ID" INTEGER PRIMARY KEY,
    "ID_Projekt" INTEGER,
    "Zone" TEXT CHECK (length("Zone") <= 20),
    "BezugMWh" REAL,
    "EinspPvMWh" REAL,
    "KwkEigenMWh" REAL,
    "KwkEinspMWh" REAL,
    "MaxBezugKW" REAL,
    "Zeitstempel" TEXT,
    "BedarfMWh" REAL
) STRICT;

CREATE TABLE "Tab_ErgebnisStromspeicher" (
    "ID" INTEGER PRIMARY KEY,
    "ID_Ergebnis" INTEGER,
    "ID_Energieanlage" INTEGER,
    "Bezeichner" TEXT,
    "Betriebsart" TEXT CHECK (length("Betriebsart") <= 50),
    "Berechnungsart" TEXT CHECK (length("Berechnungsart") <= 50),
    "Ladung_PV" REAL,
    "Ladung_BHKW" REAL,
    "Ladung_Netz" REAL,
    "Ladung_Gesamt" REAL,
    "Entladung_Gesamt" REAL,
    "Verluste_Gesamt" REAL,
    "Netzbezug_Mit" REAL,
    "Netzbezug_Ohne" REAL,
    "Einspeisung_Mit" REAL,
    "Einspeisung_Ohne" REAL,
    "Eigenverbrauchsquote" REAL,
    "Autarkiegrad" REAL,
    "Vollzyklen" REAL,
    "SoC_Min" REAL,
    "SoC_Mittel" REAL,
    "SoC_Max" REAL,
    "Zeitanteil_Untergrenze" REAL,
    "Zeitanteil_Obergrenze" REAL,
    "Zyklen_Hochrechnung" REAL,
    "Ertrag_Bezugsersparnis" REAL,
    "Ertrag_Verguetung_Entgangen" REAL,
    "Ertrag_Netzerloes" REAL,
    "Kosten_Ladung" REAL,
    "Ertrag_Leistungspreis" REAL,
    "Verschleisskosten" REAL,
    "Investition" REAL,
    "Annuitaet" REAL,
    "Jahresueberschuss" REAL,
    "Ertrag_Jahr1" REAL,
    "Ertrag_Aequivalent" REAL,
    "Amortisation_Statisch" REAL,
    "Amortisation_Dynamisch" REAL,
    "Kapitalwert" REAL,
    "Preisversion" TEXT CHECK (length("Preisversion") <= 50),
    FOREIGN KEY ("ID_Ergebnis") REFERENCES "Tab_Ergebnis" ("ID") ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_ErgebnisWaermepumpe" (
    "ID" INTEGER PRIMARY KEY,
    "ID_Ergebnis" INTEGER,
    "Waermebedarf" REAL,
    "Restwaermebedarf" REAL,
    "Waermeproduktion_WP" REAL,
    "Stromverbrauch_WP" REAL,
    "Stromverbrauch_Heizstab" REAL,
    "Kapazitaet_Pufferspeicher" REAL,
    "Min_Spitzenkesselleistung" REAL,
    "Waermebedarfsdeckung" REAL,
    "Vollbenutzungsstunden" REAL,
    "Bivalenzpunkt" REAL,
    "Deckung_Heizung" REAL,
    "Deckung_Brauchwasser" REAL,
    "Deckung_Prozess" REAL,
    FOREIGN KEY ("ID_Ergebnis") REFERENCES "Tab_Ergebnis" ("ID") ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_ErgebnisWaermepumpeModul" (
    "ID" INTEGER PRIMARY KEY,
    "ID_ErgebnisWaermepumpe" INTEGER,
    "Modul" TEXT,
    "Leistung" REAL,
    "Waermeproduktion" REAL,
    "Stromverbrauch" REAL,
    "Heizstab" REAL,
    "Betriebsstunden" REAL,
    FOREIGN KEY ("ID_ErgebnisWaermepumpe") REFERENCES "Tab_ErgebnisWaermepumpe" ("ID") ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_ErgebnisWirtschaftlichkeit" (
    "ID" INTEGER PRIMARY KEY,
    "ID_Projekt" INTEGER,
    "ID_Ergebnis" INTEGER,
    "Szenario" TEXT CHECK (length("Szenario") <= 20),
    "IstStamm" INTEGER NOT NULL DEFAULT 0 CHECK ("IstStamm" IN (0,1)),
    "Anzeige" TEXT,
    "Zeitstempel" TEXT,
    "Zinssatz" REAL,
    "Betrachtungszeitraum" INTEGER,
    "Preissteigerung_Energie" REAL,
    "Preissteigerung_Betrieb" REAL,
    "Einspeiseverguetung" REAL,
    "Investition" REAL,
    "Betriebskosten" REAL,
    "Energiekosten" REAL,
    "Einspeiseerloes" REAL,
    "BarwertAusgaben" REAL,
    "BarwertEinnahmen" REAL,
    "Restwert" REAL,
    "Kapitalwert" REAL,
    "KapitalwertDiff" REAL,
    "AnnuitaetKW" REAL,
    "AmortisationJahre" REAL,
    "Gestehungskosten" REAL,
    "Fehlgrund" TEXT,
    "IRR" REAL,
    "CO2Abgabe" REAL,
    "KWKGErloes" REAL,
    "StromkostenTarif" REAL,
    "HinweisText" TEXT,
    "KWKGVbhElektrisch" REAL,
    "EnergiesteuerErloes" REAL,
    "StromsteuerBefreiung" REAL,
    "StromsteuerEntlastung" REAL,
    "SteuerHerkunft" TEXT,
    "VermiedenArbeit" REAL,
    "VermiedenLeistung" REAL,
    "VermiedenGesamt" REAL,
    "AufschlagBetrag" REAL,
    "EinspeiseerloesPV" REAL,
    "EinspeiseerloesKWK" REAL,
    "Zuschuss" REAL,
    "PvVerguetungsform" TEXT CHECK (length("PvVerguetungsform") <= 50),
    "PvAnzulegenderWert" REAL,
    "PvMarktpraemie" REAL,
    "PvVerguetungsausfallKwh" REAL,
    "PvVerguetungsausfall" REAL,
    "PvKompensation51a" REAL,
    "PvKappungsverlustKwh" REAL,
    "PvVermiedenerBezug" REAL
) STRICT;

CREATE TABLE "Tab_ErgebnisWirtSensitivitaet" (
    "ID" INTEGER PRIMARY KEY,
    "ID_Projekt" INTEGER,
    "Parameter" TEXT CHECK (length("Parameter") <= 60),
    "KwMinus" REAL,
    "KwBasis" REAL,
    "KwPlus" REAL,
    "Zeitstempel" TEXT
) STRICT;

CREATE TABLE "Tab_Gebaeude" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_ProjektGebaeude" INTEGER NOT NULL DEFAULT 0,
    "ID_Projekt" INTEGER DEFAULT 0,
    "Gebaeudename" TEXT NOT NULL,
    "Typ" TEXT NOT NULL,
    "Beschreibung" TEXT,
    "Wohnflaeche_gesamt" REAL,
    "Bewohner" REAL,
    "Flaeche_Nutzer" REAL,
    "Interne_Waermegewinne" REAL,
    "Bauweise" REAL,
    "Fensterflaeche_Sued" REAL,
    "Fensterflaeche_Ost_West" REAL,
    "Fensterflaeche_Nord" REAL,
    "Fensterdurchlassgrad" REAL,
    "Raumsolltemperatur_Nachtabsenkung" REAL,
    "Raumsolltemperatur_Tag" REAL,
    "Raumsolltemperatur_Wochenende" REAL,
    "Raumsolltemperatur_Ferien" REAL,
    "Maximaleraumtemperatur" REAL,
    "k_Wert_Außenwand" REAL,
    "k_Wert_Fenster" REAL,
    "k_Wert_Dachflaeche" REAL,
    "k_Wert_Grundflaeche" REAL,
    "k_Wert_Sonstiges" REAL,
    "Flaeche_Außenwand" REAL,
    "gesamte_Fensterflaeche" REAL,
    "Dachflaeche" REAL,
    "Grundflaeche" REAL,
    "Sonstige_Flaechen" REAL,
    "Wohnflaeche" REAL,
    "Raumhoehe" REAL,
    "WBVK_Anschluß_Fenster_Wand" REAL,
    "WBVK_Anschluß_Wand_Dach" REAL,
    "WBVK_Anschluß_Außenwand_Kellerdecke" REAL,
    "Abmessung_Anschluß_Fenster_Wand" REAL,
    "Abmessung_Anschluß_Wand_Dach" REAL,
    "Abmessung_Anschluß_Außenwand_Kellerdecke" REAL,
    "Luftwechselrate" REAL DEFAULT 0,
    "Wochenende" REAL,
    "Ferien" REAL,
    "Ferienbeginn_1" REAL,
    "Ferienende_1" REAL,
    "Ferienbeginn_2" REAL,
    "Ferienende_2" REAL,
    "Ferienbeginn_3" REAL,
    "Ferienende_3" REAL,
    "Ferienbeginn_4" REAL,
    "Ferienende_4" REAL,
    "WW_Bedarf" REAL,
    "spez_Waermeverbrauch" REAL,
    "Waermebedarf" REAL,
    "Baualtersklasse" TEXT,
    "Gebaeudeart" TEXT,
    "Wohngebaeude_Nicht_Wohngebaeude" TEXT,
    FOREIGN KEY ("ID_ProjektGebaeude") REFERENCES "Z_ProjektGebaeude" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_Gebaeude_STAMM" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Bezeichner" TEXT NOT NULL,
    "Typ" TEXT,
    "Beschreibung" TEXT,
    "Wohnflaeche_gesamt" REAL,
    "Bewohner" REAL,
    "Flaeche_Nutzer" REAL,
    "Interne_Waermegewinne" REAL,
    "Bauweise" REAL,
    "Fensterflaeche_Sued" REAL,
    "Fensterflaeche_Ost_West" REAL,
    "Fensterflaeche_Nord" REAL,
    "Fensterdurchlassgrad" REAL,
    "Raumsolltemperatur_Nachtabsenkung" REAL,
    "Raumsolltemperatur_Tag" REAL,
    "Raumsolltemperatur_Wochenende" REAL,
    "Raumsolltemperatur_Ferien" REAL,
    "Maximaleraumtemperatur" REAL,
    "k_Wert_Außenwand" REAL,
    "k_Wert_Fenster" REAL,
    "k_Wert_Dachflaeche" REAL,
    "k_Wert_Grundflaeche" REAL,
    "k_Wert_Sonstiges" REAL,
    "Flaeche_Außenwand" REAL,
    "gesamte_Fensterflaeche" REAL,
    "Dachflaeche" REAL,
    "Grundflaeche" REAL,
    "Sonstige_Flaechen" REAL,
    "Wohnflaeche" REAL,
    "Raumhoehe" REAL,
    "WBVK_Anschluß_Fenster_Wand" REAL,
    "WBVK_Anschluß_Wand_Dach" REAL,
    "WBVK_Anschluß_Außenwand_Kellerdecke" REAL,
    "Abmessung_Anschluß_Fenster_Wand" REAL,
    "Abmessung_Anschluß_Wand_Dach" REAL,
    "Abmessung_Anschluß_Außenwand_Kellerdecke" REAL,
    "Luftwechselrate" REAL DEFAULT 0,
    "Wochenende" REAL,
    "Ferien" REAL,
    "Ferienbeginn_1" REAL,
    "Ferienende_1" REAL,
    "Ferienbeginn_2" REAL,
    "Ferienende_2" REAL,
    "Ferienbeginn_3" REAL,
    "Ferienende_3" REAL,
    "Ferienbeginn_4" REAL,
    "Ferienende_4" REAL,
    "WW_Bedarf" REAL,
    "spez_Waermeverbrauch" REAL,
    "Waermebedarf" REAL,
    "Baualtersklasse" TEXT,
    "Gebaeudeart" TEXT,
    "Wohngebaeude_Nicht_Wohngebaeude" TEXT,
    "ReadOnly" INTEGER NOT NULL DEFAULT 0 CHECK ("ReadOnly" IN (0,1))
) STRICT;

CREATE TABLE "Tab_Gesetzesparameter" (
    "ID" INTEGER PRIMARY KEY,
    "Schluessel" TEXT CHECK (length("Schluessel") <= 60),
    "Klasse" TEXT CHECK (length("Klasse") <= 40),
    "JahrVon" INTEGER,
    "Wert" REAL,
    "Einheit" TEXT CHECK (length("Einheit") <= 20),
    "Status" TEXT CHECK (length("Status") <= 12),
    "Quelle" TEXT CHECK (length("Quelle") <= 120)
) STRICT;

CREATE TABLE "Tab_Heizkessel" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Projekt" INTEGER NOT NULL,
    "Bezeichner" TEXT NOT NULL,
    "Firma" TEXT,
    "Beschreibung" TEXT,
    "Ptherm" REAL,
    "Brennstoff" INTEGER,
    "Wirkungsgrad_Gas" REAL,
    "Wirkungsgrad_Öl" REAL,
    "Investitionskosten" REAL,
    "Raumbedarf" REAL,
    "Wartungskosten" REAL,
    "Nutzungsdauer" REAL,
    "CO2" REAL,
    "SO2" REAL,
    "NOx" REAL,
    "CO" REAL,
    "Staub" REAL,
    "Betriebsbereitschaftverlust" REAL,
    "Brennwert" INTEGER NOT NULL DEFAULT 0 CHECK ("Brennwert" IN (0,1)),
    "Vorlauf" INTEGER,
    "Ruecklauf" INTEGER,
    "Wartungskosten_Einheit" TEXT CHECK (length("Wartungskosten_Einheit") <= 20)
) STRICT;

CREATE TABLE "Tab_Heizkessel_STAMM" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Bezeichner" TEXT,
    "Firma" TEXT,
    "Beschreibung" TEXT,
    "Ptherm" REAL,
    "Brennstoff" INTEGER,
    "Wirkungsgrad_Gas" REAL,
    "Wirkungsgrad_Öl" REAL,
    "Investitionskosten" REAL,
    "Raumbedarf" REAL,
    "Wartungskosten" REAL DEFAULT 0,
    "Nutzungsdauer" REAL,
    "CO2" REAL,
    "SO2" REAL,
    "NOx" REAL,
    "CO" REAL,
    "Staub" REAL,
    "Betriebsbereitschaftverlust" REAL,
    "Brennwert" INTEGER NOT NULL DEFAULT 0 CHECK ("Brennwert" IN (0,1)),
    "Vorlauf" INTEGER,
    "Ruecklauf" INTEGER,
    "ReadOnly" INTEGER NOT NULL DEFAULT 0 CHECK ("ReadOnly" IN (0,1)),
    "Wartungskosten_Einheit" TEXT CHECK (length("Wartungskosten_Einheit") <= 20)
) STRICT;

CREATE TABLE "Tab_Kenndaten" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Projekt" INTEGER DEFAULT 0,
    "ID_WP" INTEGER NOT NULL DEFAULT 0,
    "Vorlauf" INTEGER NOT NULL DEFAULT 0,
    "Temperatur" INTEGER NOT NULL DEFAULT 0,
    "COP" REAL DEFAULT 0,
    "Ptherm" REAL DEFAULT 0,
    FOREIGN KEY ("ID_WP") REFERENCES "Tab_WP" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_Kenndaten_Kuehlung" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_WP" INTEGER,
    "Vorlauf" INTEGER,
    "Temperatur" INTEGER,
    "COP" REAL,
    "Pkuehl" REAL,
    "Last" INTEGER,
    FOREIGN KEY ("ID_WP") REFERENCES "Tab_WP" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_Kenndaten_Kuehlung_STAMM" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Projekt" INTEGER DEFAULT 0,
    "ID_WP" INTEGER,
    "Vorlauf" INTEGER,
    "Temperatur" INTEGER,
    "COP" REAL,
    "Pkuehl" REAL,
    "Last" INTEGER,
    FOREIGN KEY ("ID_WP") REFERENCES "Tab_WP_STAMM" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_Kenndaten_STAMM" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_WP" INTEGER NOT NULL DEFAULT 0,
    "Vorlauf" INTEGER NOT NULL DEFAULT 0,
    "Temperatur" INTEGER NOT NULL DEFAULT 0,
    "COP" REAL DEFAULT 0,
    "Ptherm" REAL DEFAULT 0,
    "ReadOnly" INTEGER NOT NULL DEFAULT 0 CHECK ("ReadOnly" IN (0,1)),
    FOREIGN KEY ("ID_WP") REFERENCES "Tab_WP_STAMM" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_Klimadaten" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Projekt" INTEGER NOT NULL DEFAULT 0,
    "ID_Klimaregion" INTEGER NOT NULL,
    "Sol_Nord" REAL DEFAULT 0,
    "Sol_Ost" REAL DEFAULT 0,
    "Sol_Sued" REAL DEFAULT 0,
    "Sol_West" REAL DEFAULT 0,
    "Temperatur" REAL DEFAULT 0,
    "WE" INTEGER NOT NULL DEFAULT 0 CHECK ("WE" IN (0,1)),
    "TagTyp_W" REAL,
    "TagTyp_NW" REAL,
    "Globalstrahlung" REAL DEFAULT 0,
    "Direktstrahlung" REAL DEFAULT 0,
    "Diffusstrahlung" REAL DEFAULT 0,
    "Sonnenwinkel" REAL DEFAULT 0,
    FOREIGN KEY ("ID_Klimaregion") REFERENCES "Tab_Klimaregion" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_Klimadaten_STAMM" (
    "ID_Klimadaten" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Klimaregion" INTEGER NOT NULL,
    "Sol_Nord" REAL DEFAULT 0,
    "Sol_Ost" REAL DEFAULT 0,
    "Sol_Sued" REAL DEFAULT 0,
    "Sol_West" REAL DEFAULT 0,
    "Temperatur" REAL DEFAULT 0,
    "WE" INTEGER NOT NULL DEFAULT 0 CHECK ("WE" IN (0,1)),
    "TagTyp_W" REAL,
    "TagTyp_NW" REAL,
    "Globalstrahlung" REAL DEFAULT 0,
    "Direktstrahlung" REAL DEFAULT 0,
    "Diffusstrahlung" REAL DEFAULT 0,
    "Sonnenwinkel" REAL DEFAULT 0,
    FOREIGN KEY ("ID_Klimaregion") REFERENCES "Tab_Klimaregion_STAMM" ("ID_Klimaregion") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_Klimaregion" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Projekt" INTEGER NOT NULL DEFAULT 0,
    "Bezeichner" TEXT NOT NULL,
    "Longitude" REAL DEFAULT 0,
    "Latitude" REAL DEFAULT 0,
    "Details" TEXT,
    "Klimazone_DIN4710" INTEGER DEFAULT 0,
    FOREIGN KEY ("ID_Projekt") REFERENCES "Tab_Projekt" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_Klimaregion_STAMM" (
    "ID_Klimaregion" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Name" TEXT NOT NULL,
    "Longitude" REAL DEFAULT 0,
    "Latitude" REAL DEFAULT 0,
    "Details" TEXT,
    "ReadOnly" INTEGER NOT NULL DEFAULT 0 CHECK ("ReadOnly" IN (0,1))
) STRICT;

CREATE TABLE "Tab_Kostenfaktor" (
    "StammID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Bezeichnung" TEXT,
    "IsMainComponent" INTEGER NOT NULL DEFAULT 0 CHECK ("IsMainComponent" IN (0,1))
) STRICT;

CREATE TABLE "Tab_KostenGruppenKatalog" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "GruppenName" TEXT
) STRICT;

CREATE TABLE "Tab_KostenKomponente" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Komponente" TEXT
) STRICT;

CREATE TABLE "Tab_Kostenprofil" (
    "ID" INTEGER PRIMARY KEY,
    "ID_Projekt" INTEGER,
    "Bezeichner" TEXT,
    "Monatswerte" TEXT,
    "Wochenwerte" TEXT,
    FOREIGN KEY ("ID_Projekt") REFERENCES "Tab_Projekt" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_KostenVorlage" (
    "ID" INTEGER PRIMARY KEY,
    "KomponentenID" INTEGER,
    "KategorieID" INTEGER,
    "Name" TEXT CHECK (length("Name") <= 100),
    "IstStandard" INTEGER NOT NULL DEFAULT 0 CHECK ("IstStandard" IN (0,1)),
    "ReadOnly" INTEGER NOT NULL DEFAULT 0 CHECK ("ReadOnly" IN (0,1)),
    "Bemerkung" TEXT,
    "GeaendertAm" TEXT
) STRICT;

CREATE TABLE "Tab_KostenVorlagePosition" (
    "ID" INTEGER PRIMARY KEY,
    "VorlageID" INTEGER,
    "StammID" INTEGER,
    "Bezeichnung" TEXT,
    "Kostenart" TEXT CHECK (length("Kostenart") <= 20),
    "Bemessung" TEXT CHECK (length("Bemessung") <= 30),
    "Satz" REAL,
    "BetragNetto" REAL,
    "IstErloes" INTEGER NOT NULL DEFAULT 0 CHECK ("IstErloes" IN (0,1)),
    "Nutzungsdauer" REAL,
    "Empfehlung_von" REAL,
    "Empfehlung_bis" REAL,
    "Sortierung" INTEGER,
    "IstPflicht" INTEGER NOT NULL DEFAULT 0 CHECK ("IstPflicht" IN (0,1)),
    FOREIGN KEY ("VorlageID") REFERENCES "Tab_KostenVorlage" ("ID") ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_Kraftwerkspark" (
    "ID" INTEGER PRIMARY KEY,
    "Bezeichner" TEXT CHECK (length("Bezeichner") <= 100),
    "Wirkungsgrad" REAL,
    "CO2" REAL,
    "SO2" REAL,
    "NOx" REAL,
    "Netzverluste" REAL
) STRICT;

CREATE TABLE "Tab_Preisreihe" (
    "ID" INTEGER PRIMARY KEY,
    "ID_Projekt" INTEGER,
    "Bezeichner" TEXT,
    "Jahr" INTEGER,
    "Aufloesung" TEXT CHECK (length("Aufloesung") <= 50),
    "Einheit" TEXT CHECK (length("Einheit") <= 50),
    "ID_Energietraeger" INTEGER,
    FOREIGN KEY ("ID_Projekt") REFERENCES "Tab_Projekt" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_PreisreiheDaten" (
    "ID" INTEGER PRIMARY KEY,
    "ID_Preisreihe" INTEGER,
    "Wert" REAL,
    FOREIGN KEY ("ID_Preisreihe") REFERENCES "Tab_Preisreihe" ("ID") ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_Projekt" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Projektname" TEXT NOT NULL,
    "Bearbeiter" TEXT,
    "Beschreibung" TEXT,
    "Kunde" TEXT,
    "Aenderungsdatum" TEXT,
    "ID_Klimaregion" INTEGER,
    "Erstelldatum" TEXT,
    "Emission_Berechnungsmodus" TEXT CHECK (length("Emission_Berechnungsmodus") <= 10)
) STRICT;

CREATE TABLE "Tab_ProjektPhotovoltaik" (
    "ID" INTEGER PRIMARY KEY,
    "ID_Projekt" INTEGER,
    "Aktiv" INTEGER NOT NULL DEFAULT 0 CHECK ("Aktiv" IN (0,1)),
    "Vermarktungsform" TEXT CHECK (length("Vermarktungsform") <= 30),
    "Einspeiseart" TEXT CHECK (length("Einspeiseart") <= 20),
    "Inbetriebnahme" TEXT,
    "KwpOverride" REAL,
    "AwOverride" REAL,
    "DvEntgelt" REAL,
    "PpaPreis" REAL,
    "PpaSpotAufschlag" REAL,
    "Par51_Anwenden" TEXT CHECK (length("Par51_Anwenden") <= 20),
    "IMSys_Einbaujahr" INTEGER,
    "AusfallanteilProzent" REAL,
    "Par51a_Kompensieren" INTEGER NOT NULL DEFAULT 0 CHECK ("Par51a_Kompensieren" IN (0,1)),
    "Kappung60_Anwenden" TEXT CHECK (length("Kappung60_Anwenden") <= 20),
    "MarktwertJahresmittel" REAL,
    "MarktwertEntwicklung" REAL,
    "BezugAusPreisreihe" INTEGER NOT NULL DEFAULT 0 CHECK ("BezugAusPreisreihe" IN (0,1)),
    "GeaendertAm" TEXT
) STRICT;

CREATE TABLE "Tab_ProjektTarif" (
    "ID" INTEGER PRIMARY KEY,
    "ID_Projekt" INTEGER,
    "Aktiv" INTEGER NOT NULL DEFAULT 0 CHECK ("Aktiv" IN (0,1)),
    "Winter_Von" INTEGER,
    "Winter_Bis" INTEGER,
    "HT_Von" INTEGER,
    "HT_Bis" INTEGER,
    "Bezug_W_HT" REAL,
    "Bezug_W_NT" REAL,
    "Bezug_S_HT" REAL,
    "Bezug_S_NT" REAL,
    "Einsp_W_HT" REAL,
    "Einsp_W_NT" REAL,
    "Einsp_S_HT" REAL,
    "Einsp_S_NT" REAL,
    "Staffel_Grenze" REAL,
    "Staffel_Preis1" REAL,
    "Staffel_Preis2" REAL,
    "GeaendertAm" TEXT,
    "Tarif_Modus" TEXT CHECK (length("Tarif_Modus") <= 12),
    "Tarif_GueltigAb" TEXT,
    "Bezug_Arbeit" REAL,
    "Bezug_Grundpreis" REAL,
    "Bezug_Leistungsmodell" TEXT CHECK (length("Bezug_Leistungsmodell") <= 24),
    "Bezug_Monatspreis" REAL,
    "Bezug_Stufe1_KW" REAL,
    "Bezug_Stufe1_Sommer" REAL,
    "Bezug_Stufe1_Winter" REAL,
    "Bezug_Stufe2_KW" REAL,
    "Bezug_Stufe2_Sommer" REAL,
    "Bezug_Stufe2_Winter" REAL,
    "Bezug_Stufe3_KW" REAL,
    "Bezug_Stufe3_Sommer" REAL,
    "Bezug_Stufe3_Winter" REAL,
    "Bezug_Stufe4_KW" REAL,
    "Bezug_Stufe4_Sommer" REAL,
    "Bezug_Stufe4_Winter" REAL,
    "Rest_Arbeit" REAL,
    "Rest_Grundpreis" REAL,
    "Rest_Leistungsmodell" TEXT CHECK (length("Rest_Leistungsmodell") <= 24),
    "Rest_Monatspreis" REAL,
    "Rest_Stufe1_KW" REAL,
    "Rest_Stufe1_Sommer" REAL,
    "Rest_Stufe1_Winter" REAL,
    "Rest_Stufe2_KW" REAL,
    "Rest_Stufe2_Sommer" REAL,
    "Rest_Stufe2_Winter" REAL,
    "Rest_Stufe3_KW" REAL,
    "Rest_Stufe3_Sommer" REAL,
    "Rest_Stufe3_Winter" REAL,
    "Rest_Stufe4_KW" REAL,
    "Rest_Stufe4_Sommer" REAL,
    "Rest_Stufe4_Winter" REAL,
    "Einsp_Arbeit" REAL,
    "Einsp_Grundpreis" REAL,
    FOREIGN KEY ("ID_Projekt") REFERENCES "Tab_Projekt" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_ProjektWerte" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ProjektID" INTEGER DEFAULT 0,
    "StammID" INTEGER DEFAULT 0,
    "KomponentenID" INTEGER DEFAULT 0,
    "KategorieID" INTEGER DEFAULT 0,
    "EingegebenerWert" REAL DEFAULT 0,
    "Worstcase" REAL DEFAULT 0,
    "Bestcase" REAL DEFAULT 0,
    "Nutzungsdauer" REAL DEFAULT 0,
    "Worstcase_Nutzungsdauer" REAL DEFAULT 0,
    "Bestcase_Nutzungsdauer" REAL DEFAULT 0,
    "Einheit" TEXT,
    "Gruppe" TEXT,
    "Kostenart" TEXT CHECK (length("Kostenart") <= 20),
    "Bemessung" TEXT CHECK (length("Bemessung") <= 30),
    "IstErloes" INTEGER NOT NULL DEFAULT 0 CHECK ("IstErloes" IN (0,1)),
    "Menge" REAL,
    "Einheitpreis" REAL,
    "VorlageID" INTEGER,
    "StartJahr" INTEGER,
    "ID_Anlage" INTEGER,
    "ID_AnlageGeraet" INTEGER,
    "IstPflicht" INTEGER NOT NULL DEFAULT 0 CHECK ("IstPflicht" IN (0,1)),
    FOREIGN KEY ("StammID") REFERENCES "Tab_Kostenfaktor" ("StammID") ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY ("Gruppe") REFERENCES "Tab_KostenGruppenKatalog" ("GruppenName"),
    FOREIGN KEY ("KomponentenID") REFERENCES "Tab_KostenKomponente" ("ID") ON UPDATE CASCADE,
    FOREIGN KEY ("ProjektID") REFERENCES "Tab_Projekt" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_ProjektWirtschaftlichkeit" (
    "ID" INTEGER PRIMARY KEY,
    "ID_Projekt" INTEGER,
    "Zinssatz" REAL,
    "Betrachtungszeitraum" INTEGER,
    "Preissteigerung_Energie" REAL,
    "Preissteigerung_Betrieb" REAL,
    "Einspeiseverguetung" REAL,
    "GeaendertAm" TEXT,
    "CO2_Preis" REAL,
    "KWKG_Bonus" REAL,
    "KWKG_Vbh_Jahresdeckel" REAL,
    "KWKG_Vbh_Kontingent" REAL,
    "KWKG_Bonus_Einspeisung" REAL,
    "ID_Kraftwerkspark" INTEGER,
    "RefKessel_Wirkungsgrad" REAL,
    "RefKessel_ID_Brennstoff" INTEGER,
    "KWKG_Stichtag" TEXT,
    "KWKG_Inbetriebnahme" TEXT,
    "KWKG_Abschlag_Negativ" REAL,
    "Unternehmensart" TEXT CHECK (length("Unternehmensart") <= 24),
    "Raeumlicher_Zusammenhang" INTEGER NOT NULL DEFAULT 0 CHECK ("Raeumlicher_Zusammenhang" IN (0,1)),
    "Hocheffizienz_Nachweis" INTEGER NOT NULL DEFAULT 0 CHECK ("Hocheffizienz_Nachweis" IN (0,1)),
    "Jahresnutzungsgrad" REAL,
    "Energiesteuer_Wahl" TEXT CHECK (length("Energiesteuer_Wahl") <= 20),
    "Aufteilung_Methode" TEXT CHECK (length("Aufteilung_Methode") <= 30),
    "Aufschlaege_Anwenden" INTEGER NOT NULL DEFAULT 0 CHECK ("Aufschlaege_Anwenden" IN (0,1)),
    "Einspeiseverguetung_KWK" REAL,
    "Bilanz_Jahr" INTEGER,
    "Emissions_Methode" TEXT CHECK (length("Emissions_Methode") <= 30),
    "Biomasse_Konvention" TEXT CHECK (length("Biomasse_Konvention") <= 30),
    "Biomasse_Nachweis" TEXT CHECK (length("Biomasse_Nachweis") <= 30),
    "KWKG_Tatbestand" TEXT CHECK (length("KWKG_Tatbestand") <= 30),
    "KWKG_Anlagenart" TEXT CHECK (length("KWKG_Anlagenart") <= 20),
    "KWKG_Kostenanteil" REAL,
    "KWKG_Pauschalmodus" INTEGER NOT NULL DEFAULT 0 CHECK ("KWKG_Pauschalmodus" IN (0,1)),
    FOREIGN KEY ("ID_Projekt") REFERENCES "Tab_Projekt" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_Prozesstyp" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Prozesswaerme" INTEGER NOT NULL DEFAULT 0,
    "ID_Projekt" INTEGER NOT NULL DEFAULT 0,
    "Typname" TEXT NOT NULL,
    "Beschreibung" TEXT,
    "1" REAL,
    "2" REAL,
    "3" REAL,
    "4" REAL,
    "5" REAL,
    "6" REAL,
    "7" REAL,
    "8" REAL,
    "9" REAL,
    "10" REAL,
    "11" REAL,
    "12" REAL,
    "13" REAL,
    "14" REAL,
    "15" REAL,
    "16" REAL,
    "17" REAL,
    "18" REAL,
    "19" REAL,
    "20" REAL,
    "21" REAL,
    "22" REAL,
    "23" REAL,
    "24" REAL,
    "25" REAL,
    "26" REAL,
    "27" REAL,
    "28" REAL,
    "29" REAL,
    "30" REAL,
    "31" REAL,
    "32" REAL,
    "33" REAL,
    "34" REAL,
    "35" REAL,
    "36" REAL,
    "37" REAL,
    "38" REAL,
    "39" REAL,
    "40" REAL,
    "41" REAL,
    "42" REAL,
    "43" REAL,
    "44" REAL,
    "45" REAL,
    "46" REAL,
    "47" REAL,
    "48" REAL,
    "49" REAL,
    "50" REAL,
    "51" REAL,
    "52" REAL,
    "53" REAL,
    "54" REAL,
    "55" REAL,
    "56" REAL,
    "57" REAL,
    "58" REAL,
    "59" REAL,
    "60" REAL,
    "61" REAL,
    "62" REAL,
    "63" REAL,
    "64" REAL,
    "65" REAL,
    "66" REAL,
    "67" REAL,
    "68" REAL,
    "69" REAL,
    "70" REAL,
    "71" REAL,
    "72" REAL,
    "73" REAL,
    "74" REAL,
    "75" REAL,
    "76" REAL,
    "77" REAL,
    "78" REAL,
    "79" REAL,
    "80" REAL,
    "81" REAL,
    "82" REAL,
    "83" REAL,
    "84" REAL,
    "85" REAL,
    "86" REAL,
    "87" REAL,
    "88" REAL,
    "89" REAL,
    "90" REAL,
    "91" REAL,
    "92" REAL,
    "93" REAL,
    "94" REAL,
    "95" REAL,
    "96" REAL,
    "97" REAL,
    "98" REAL,
    "99" REAL,
    "100" REAL,
    "101" REAL,
    "102" REAL,
    "103" REAL,
    "104" REAL,
    "105" REAL,
    "106" REAL,
    "107" REAL,
    "108" REAL,
    "109" REAL,
    "110" REAL,
    "111" REAL,
    "112" REAL,
    "113" REAL,
    "114" REAL,
    "115" REAL,
    "116" REAL,
    "117" REAL,
    "118" REAL,
    "119" REAL,
    "120" REAL,
    "121" REAL,
    "122" REAL,
    "123" REAL,
    "124" REAL,
    "125" REAL,
    "126" REAL,
    "127" REAL,
    "128" REAL,
    "129" REAL,
    "130" REAL,
    "131" REAL,
    "132" REAL,
    "133" REAL,
    "134" REAL,
    "135" REAL,
    "136" REAL,
    "137" REAL,
    "138" REAL,
    "139" REAL,
    "140" REAL,
    "141" REAL,
    "142" REAL,
    "143" REAL,
    "144" REAL,
    "145" REAL,
    "146" REAL,
    "147" REAL,
    "148" REAL,
    "149" REAL,
    "150" REAL,
    "151" REAL,
    "152" REAL,
    "153" REAL,
    "154" REAL,
    "155" REAL,
    "156" REAL,
    "157" REAL,
    "158" REAL,
    "159" REAL,
    "160" REAL,
    "161" REAL,
    "162" REAL,
    "163" REAL,
    "164" REAL,
    "165" REAL,
    "166" REAL,
    "167" REAL,
    "168" REAL,
    "ReadOnly" INTEGER NOT NULL DEFAULT 0 CHECK ("ReadOnly" IN (0,1)),
    FOREIGN KEY ("ID_Prozesswaerme") REFERENCES "Tab_Prozesswaerme" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_Prozesstyp_STAMM" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Bezeichner" TEXT NOT NULL,
    "Beschreibung" TEXT,
    "1" REAL,
    "2" REAL,
    "3" REAL,
    "4" REAL,
    "5" REAL,
    "6" REAL,
    "7" REAL,
    "8" REAL,
    "9" REAL,
    "10" REAL,
    "11" REAL,
    "12" REAL,
    "13" REAL,
    "14" REAL,
    "15" REAL,
    "16" REAL,
    "17" REAL,
    "18" REAL,
    "19" REAL,
    "20" REAL,
    "21" REAL,
    "22" REAL,
    "23" REAL,
    "24" REAL,
    "25" REAL,
    "26" REAL,
    "27" REAL,
    "28" REAL,
    "29" REAL,
    "30" REAL,
    "31" REAL,
    "32" REAL,
    "33" REAL,
    "34" REAL,
    "35" REAL,
    "36" REAL,
    "37" REAL,
    "38" REAL,
    "39" REAL,
    "40" REAL,
    "41" REAL,
    "42" REAL,
    "43" REAL,
    "44" REAL,
    "45" REAL,
    "46" REAL,
    "47" REAL,
    "48" REAL,
    "49" REAL,
    "50" REAL,
    "51" REAL,
    "52" REAL,
    "53" REAL,
    "54" REAL,
    "55" REAL,
    "56" REAL,
    "57" REAL,
    "58" REAL,
    "59" REAL,
    "60" REAL,
    "61" REAL,
    "62" REAL,
    "63" REAL,
    "64" REAL,
    "65" REAL,
    "66" REAL,
    "67" REAL,
    "68" REAL,
    "69" REAL,
    "70" REAL,
    "71" REAL,
    "72" REAL,
    "73" REAL,
    "74" REAL,
    "75" REAL,
    "76" REAL,
    "77" REAL,
    "78" REAL,
    "79" REAL,
    "80" REAL,
    "81" REAL,
    "82" REAL,
    "83" REAL,
    "84" REAL,
    "85" REAL,
    "86" REAL,
    "87" REAL,
    "88" REAL,
    "89" REAL,
    "90" REAL,
    "91" REAL,
    "92" REAL,
    "93" REAL,
    "94" REAL,
    "95" REAL,
    "96" REAL,
    "97" REAL,
    "98" REAL,
    "99" REAL,
    "100" REAL,
    "101" REAL,
    "102" REAL,
    "103" REAL,
    "104" REAL,
    "105" REAL,
    "106" REAL,
    "107" REAL,
    "108" REAL,
    "109" REAL,
    "110" REAL,
    "111" REAL,
    "112" REAL,
    "113" REAL,
    "114" REAL,
    "115" REAL,
    "116" REAL,
    "117" REAL,
    "118" REAL,
    "119" REAL,
    "120" REAL,
    "121" REAL,
    "122" REAL,
    "123" REAL,
    "124" REAL,
    "125" REAL,
    "126" REAL,
    "127" REAL,
    "128" REAL,
    "129" REAL,
    "130" REAL,
    "131" REAL,
    "132" REAL,
    "133" REAL,
    "134" REAL,
    "135" REAL,
    "136" REAL,
    "137" REAL,
    "138" REAL,
    "139" REAL,
    "140" REAL,
    "141" REAL,
    "142" REAL,
    "143" REAL,
    "144" REAL,
    "145" REAL,
    "146" REAL,
    "147" REAL,
    "148" REAL,
    "149" REAL,
    "150" REAL,
    "151" REAL,
    "152" REAL,
    "153" REAL,
    "154" REAL,
    "155" REAL,
    "156" REAL,
    "157" REAL,
    "158" REAL,
    "159" REAL,
    "160" REAL,
    "161" REAL,
    "162" REAL,
    "163" REAL,
    "164" REAL,
    "165" REAL,
    "166" REAL,
    "167" REAL,
    "168" REAL,
    "ReadOnly" INTEGER NOT NULL DEFAULT 0 CHECK ("ReadOnly" IN (0,1))
) STRICT;

CREATE TABLE "Tab_Prozesswaerme" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Projekt" INTEGER NOT NULL,
    "Bezeichner" TEXT NOT NULL,
    "Typ" TEXT,
    "Beschreibung" TEXT,
    "Monat_1" REAL,
    "Monat_2" REAL,
    "Monat_3" REAL,
    "Monat_4" REAL,
    "Monat_5" REAL,
    "Monat_6" REAL,
    "Monat_7" REAL,
    "Monat_8" REAL,
    "Monat_9" REAL,
    "Monat_10" REAL,
    "Monat_11" REAL,
    "Monat_12" REAL,
    "ReadOnly" INTEGER NOT NULL DEFAULT 0 CHECK ("ReadOnly" IN (0,1))
) STRICT;

CREATE TABLE "Tab_Prozesswaerme_STAMM" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Bezeichner" TEXT NOT NULL,
    "Typ" TEXT,
    "Beschreibung" TEXT,
    "Monat_1" REAL,
    "Monat_2" REAL,
    "Monat_3" REAL,
    "Monat_4" REAL,
    "Monat_5" REAL,
    "Monat_6" REAL,
    "Monat_7" REAL,
    "Monat_8" REAL,
    "Monat_9" REAL,
    "Monat_10" REAL,
    "Monat_11" REAL,
    "Monat_12" REAL,
    "ReadOnly" INTEGER NOT NULL DEFAULT 0 CHECK ("ReadOnly" IN (0,1))
) STRICT;

CREATE TABLE "Tab_Pufferspeicher" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Projekt" INTEGER NOT NULL,
    "Bezeichner" TEXT NOT NULL,
    "Hersteller" TEXT,
    "Speichertyp" TEXT,
    "Bereitschaftsverluste" REAL,
    "Gesamtvolumen" INTEGER,
    "Investitionskosten" REAL,
    "Verwendung" TEXT CHECK (length("Verwendung") <= 50),
    "Vorlauf" INTEGER,
    "Ruecklauf" INTEGER,
    "Schwelle_Ein" REAL,
    "Schwelle_Aus" REAL,
    "Schwelle_Aus_Nachrang" REAL,
    "Entladeprio" INTEGER,
    "Schwelle_Reserve" REAL,
    "Nutzung_Heizung" INTEGER NOT NULL DEFAULT 0 CHECK ("Nutzung_Heizung" IN (0,1)),
    "Nutzung_Brauchwasser" INTEGER NOT NULL DEFAULT 0 CHECK ("Nutzung_Brauchwasser" IN (0,1)),
    "Nutzung_Prozess" INTEGER NOT NULL DEFAULT 0 CHECK ("Nutzung_Prozess" IN (0,1)),
    "Schichten_Anzahl" INTEGER,
    "Hoehe" REAL,
    "Lambda_Eff" REAL,
    "T_Nutz_BW" REAL,
    "Entnahme_Heizung" REAL,
    "Entnahme_BW" REAL,
    "Entnahme_Prozess" REAL,
    "Ladeleistung_Max" REAL,
    "Entladeleistung_Max" REAL,
    FOREIGN KEY ("ID_Projekt") REFERENCES "Tab_Projekt" ("ID") ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_Pufferspeicher_STAMM" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Bezeichner" TEXT NOT NULL,
    "Hersteller" TEXT,
    "Speichertyp" TEXT,
    "Bereitschaftsverluste" REAL DEFAULT 0,
    "Gesamtvolumen" INTEGER DEFAULT 0,
    "Investitionskosten" REAL DEFAULT 0,
    "ReadOnly" INTEGER NOT NULL DEFAULT 0 CHECK ("ReadOnly" IN (0,1))
) STRICT;

CREATE TABLE "Tab_PV" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Projekt" INTEGER NOT NULL,
    "Bezeichner" TEXT NOT NULL,
    "Firma" TEXT,
    "Beschreibung" TEXT,
    "Leistung" REAL,
    "Wirkungsgrad" REAL,
    "U_Mpp" REAL,
    "U_Leerlauf" REAL,
    "I_Mpp" REAL,
    "I_Kurzschluss" REAL,
    "alpha_SC" REAL,
    "beta_OC" REAL,
    "gamma_PMP" REAL,
    "T_NOCT" REAL,
    "Laenge" REAL,
    "Breite" REAL,
    "Modulkosten" REAL
) STRICT;

CREATE TABLE "Tab_PV_STAMM" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Bezeichner" TEXT,
    "Firma" TEXT,
    "Beschreibung" TEXT,
    "Leistung" REAL DEFAULT 0,
    "Wirkungsgrad" REAL DEFAULT 0,
    "U_Mpp" REAL DEFAULT 0,
    "U_Leerlauf" REAL DEFAULT 0,
    "I_Mpp" REAL DEFAULT 0,
    "I_Kurzschluss" REAL DEFAULT 0,
    "alpha_SC" REAL DEFAULT 0,
    "beta_OC" REAL DEFAULT 0,
    "gamma_PMP" REAL DEFAULT 0,
    "T_NOCT" REAL DEFAULT 0,
    "Laenge" REAL DEFAULT 0,
    "Breite" REAL DEFAULT 0,
    "Modulkosten" REAL DEFAULT 0,
    "ReadOnly" INTEGER NOT NULL DEFAULT 0 CHECK ("ReadOnly" IN (0,1))
) STRICT;

CREATE TABLE "Tab_Quellprofil" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Projekt" INTEGER,
    "Bezeichner" TEXT,
    "Betriebsart" TEXT CHECK (length("Betriebsart") <= 50),
    "Einheit" TEXT CHECK (length("Einheit") <= 50),
    "Beschreibung" TEXT
) STRICT;

CREATE TABLE "Tab_QuellprofilDaten" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Quellprofil" INTEGER NOT NULL,
    "Index" INTEGER NOT NULL,
    "Wert" REAL,
    FOREIGN KEY ("ID_Quellprofil") REFERENCES "Tab_Quellprofil" ("ID") ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_Solar" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Projekt" INTEGER NOT NULL,
    "ID_Klimaregion" INTEGER NOT NULL,
    "Temperatur" REAL,
    "Sol_Nord" REAL,
    "Sol_Ost" REAL,
    "Sol_Sued" REAL,
    "Sol_West" REAL,
    "Globalstrahlung" REAL,
    "Direktstrahlung" REAL,
    "Diffusstrahlung" REAL,
    "Sonnenwinkel" REAL,
    FOREIGN KEY ("ID_Klimaregion") REFERENCES "Tab_Klimaregion" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_Solar_STAMM" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Klimaregion" INTEGER NOT NULL,
    "Temperatur" REAL,
    "Sol_Nord" REAL,
    "Sol_Ost" REAL,
    "Sol_Sued" REAL,
    "Sol_West" REAL,
    "Globalstrahlung" REAL,
    "Direktstrahlung" REAL,
    "Diffusstrahlung" REAL,
    "Sonnenwinkel" REAL,
    FOREIGN KEY ("ID_Klimaregion") REFERENCES "Tab_Klimaregion_STAMM" ("ID_Klimaregion") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_Solarganglinie" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Projekt" INTEGER DEFAULT 0,
    "Bezeichner" TEXT,
    "Beschreibung" TEXT
) STRICT;

CREATE TABLE "Tab_Solarganglinie_STAMM" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Bezeichner" TEXT,
    "Beschreibung" TEXT,
    "ReadOnly" INTEGER NOT NULL DEFAULT 0 CHECK ("ReadOnly" IN (0,1))
) STRICT;

CREATE TABLE "Tab_SolarganglinieDaten" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Ganglinie" INTEGER NOT NULL,
    "Wert" REAL,
    FOREIGN KEY ("ID_Ganglinie") REFERENCES "Tab_Solarganglinie" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_SolarganglinieDaten_STAMM" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Ganglinie" INTEGER NOT NULL,
    "Wert" REAL,
    "ReadOnly" INTEGER NOT NULL DEFAULT 0 CHECK ("ReadOnly" IN (0,1))
) STRICT;

CREATE TABLE "Tab_Solarkollektoren" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Projekt" INTEGER NOT NULL DEFAULT 0,
    "Bezeichner" TEXT NOT NULL,
    "Firma" TEXT,
    "Beschreibung" TEXT,
    "Kollektortyp" TEXT,
    "Modulflaeche" REAL DEFAULT 0,
    "Aperturflaeche" REAL DEFAULT 0,
    "h0" REAL DEFAULT 0,
    "k1" REAL DEFAULT 0,
    "k2" REAL DEFAULT 0,
    "Kdir" REAL DEFAULT 0,
    "Kdfu" REAL DEFAULT 0,
    "Investitionskosten" REAL DEFAULT 0,
    "Vorlauf" INTEGER DEFAULT 0,
    "Ruecklauf" INTEGER DEFAULT 0
) STRICT;

CREATE TABLE "Tab_Solarkollektoren_STAMM" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Bezeichner" TEXT NOT NULL,
    "Firma" TEXT,
    "Beschreibung" TEXT,
    "Kollektortyp" TEXT,
    "Modulflaeche" REAL DEFAULT 0,
    "Aperturflaeche" REAL DEFAULT 0,
    "h0" REAL DEFAULT 0,
    "k1" REAL DEFAULT 0,
    "k2" REAL DEFAULT 0,
    "Kdir" REAL DEFAULT 0,
    "Kdfu" REAL DEFAULT 0,
    "Investitionskosten" REAL DEFAULT 0,
    "Vorlauf" INTEGER DEFAULT 0,
    "Ruecklauf" INTEGER DEFAULT 0,
    "ReadOnly" INTEGER NOT NULL DEFAULT 0 CHECK ("ReadOnly" IN (0,1))
) STRICT;

CREATE TABLE "Tab_Stromganglinie" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Projekt" INTEGER DEFAULT 0,
    "Bezeichner" TEXT,
    "Zeitinterval" INTEGER DEFAULT 0
) STRICT;

CREATE TABLE "Tab_Stromganglinie_STAMM" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Bezeichner" TEXT,
    "Zeitinterval" INTEGER DEFAULT 0,
    "ReadOnly" INTEGER NOT NULL DEFAULT 0 CHECK ("ReadOnly" IN (0,1))
) STRICT;

CREATE TABLE "Tab_StromganglinieDaten" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Ganglinie" INTEGER NOT NULL,
    "Wert" REAL,
    FOREIGN KEY ("ID_Ganglinie") REFERENCES "Tab_Stromganglinie" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_StromganglinieDaten_STAMM" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Ganglinie" INTEGER NOT NULL,
    "Wert" REAL,
    "ReadOnly" INTEGER NOT NULL DEFAULT 0 CHECK ("ReadOnly" IN (0,1)),
    FOREIGN KEY ("ID_Ganglinie") REFERENCES "Tab_Stromganglinie_STAMM" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_Stromspeicher" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Projekt" INTEGER NOT NULL,
    "Bezeichner" TEXT NOT NULL,
    "Typ" TEXT,
    "Leistung" REAL,
    "Energie" REAL,
    "Degradation" REAL,
    "Ladezustand" REAL,
    "Modulkosten" REAL,
    "Wirkungsgrad_RT" REAL,
    "Zyklen_Zugesichert" INTEGER,
    "Verschleisskosten" REAL,
    "Leistungskosten" REAL,
    "Investition_Fix" REAL,
    "Standby_Verbrauch" REAL
) STRICT;

CREATE TABLE "Tab_Stromspeicher_STAMM" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Bezeichner" TEXT NOT NULL,
    "Typ" TEXT,
    "Leistung" REAL DEFAULT 0,
    "Energie" REAL DEFAULT 0,
    "Degradation" REAL DEFAULT 0,
    "Ladezustand" REAL DEFAULT 0,
    "Modulkosten" REAL DEFAULT 0,
    "ReadOnly" INTEGER NOT NULL DEFAULT 0 CHECK ("ReadOnly" IN (0,1)),
    "Wirkungsgrad_RT" REAL,
    "Zyklen_Zugesichert" INTEGER,
    "Verschleisskosten" REAL,
    "Leistungskosten" REAL,
    "Investition_Fix" REAL,
    "Standby_Verbrauch" REAL
) STRICT;

CREATE TABLE "Tab_StromspeicherVariante" (
    "ID" INTEGER PRIMARY KEY,
    "ID_Energieanlage" INTEGER,
    "Betriebsart" TEXT CHECK (length("Betriebsart") <= 50),
    "PV_Zulaessig" INTEGER NOT NULL DEFAULT 0 CHECK ("PV_Zulaessig" IN (0,1)),
    "BHKW_Ueberschuss_Zulaessig" INTEGER NOT NULL DEFAULT 0 CHECK ("BHKW_Ueberschuss_Zulaessig" IN (0,1)),
    "BHKW_Stromgefuehrt" INTEGER NOT NULL DEFAULT 0 CHECK ("BHKW_Stromgefuehrt" IN (0,1)),
    "Netzentladung" INTEGER NOT NULL DEFAULT 0 CHECK ("Netzentladung" IN (0,1)),
    "SoC_Min_Prozent" REAL,
    "SoC_Max_Prozent" REAL,
    "Berechnungsart" TEXT CHECK (length("Berechnungsart") <= 50),
    "Preisquelle" TEXT CHECK (length("Preisquelle") <= 50),
    "Kompatibilitaetsmodus" INTEGER NOT NULL DEFAULT 0 CHECK ("Kompatibilitaetsmodus" IN (0,1)),
    "Kapitalzins" REAL,
    "Nutzungsdauer" REAL,
    "L_P" REAL,
    "A_Netzlade" REAL,
    "Aktiv" INTEGER NOT NULL DEFAULT 0 CHECK ("Aktiv" IN (0,1)),
    "Ladeschwellwert" REAL,
    "ID_Preisreihe" INTEGER,
    "ID_Kostenprofil" INTEGER,
    "Aufschlag_Anwenden" INTEGER NOT NULL DEFAULT 0 CHECK ("Aufschlag_Anwenden" IN (0,1)),
    FOREIGN KEY ("ID_Energieanlage") REFERENCES "Tab_Energieanlagen" ("ID") ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_Stromverbraucher" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Projekt" INTEGER DEFAULT 0,
    "Bezeichner" TEXT NOT NULL,
    "Typ" TEXT,
    "Beschreibung" TEXT,
    "Monat_1" REAL,
    "Monat_2" REAL,
    "Monat_3" REAL,
    "Monat_4" REAL,
    "Monat_5" REAL,
    "Monat_6" REAL,
    "Monat_7" REAL,
    "Monat_8" REAL,
    "Monat_9" REAL,
    "Monat_10" REAL,
    "Monat_11" REAL,
    "Monat_12" REAL
) STRICT;

CREATE TABLE "Tab_Stromverbraucher_STAMM" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Bezeichner" TEXT NOT NULL,
    "Typ" TEXT,
    "Beschreibung" TEXT,
    "Monat_1" REAL,
    "Monat_2" REAL,
    "Monat_3" REAL,
    "Monat_4" REAL,
    "Monat_5" REAL,
    "Monat_6" REAL,
    "Monat_7" REAL,
    "Monat_8" REAL,
    "Monat_9" REAL,
    "Monat_10" REAL,
    "Monat_11" REAL,
    "Monat_12" REAL,
    "ReadOnly" INTEGER NOT NULL DEFAULT 0 CHECK ("ReadOnly" IN (0,1))
) STRICT;

CREATE TABLE "Tab_Stromverbrauchertyp" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Stromverbraucher" INTEGER NOT NULL DEFAULT 0,
    "ID_Projekt" INTEGER DEFAULT 0,
    "Typname" TEXT,
    "Beschreibung" TEXT,
    "1" REAL,
    "2" REAL,
    "3" REAL,
    "4" REAL,
    "5" REAL,
    "6" REAL,
    "7" REAL,
    "8" REAL,
    "9" REAL,
    "10" REAL,
    "11" REAL,
    "12" REAL,
    "13" REAL,
    "14" REAL,
    "15" REAL,
    "16" REAL,
    "17" REAL,
    "18" REAL,
    "19" REAL,
    "20" REAL,
    "21" REAL,
    "22" REAL,
    "23" REAL,
    "24" REAL,
    "25" REAL,
    "26" REAL,
    "27" REAL,
    "28" REAL,
    "29" REAL,
    "30" REAL,
    "31" REAL,
    "32" REAL,
    "33" REAL,
    "34" REAL,
    "35" REAL,
    "36" REAL,
    "37" REAL,
    "38" REAL,
    "39" REAL,
    "40" REAL,
    "41" REAL,
    "42" REAL,
    "43" REAL,
    "44" REAL,
    "45" REAL,
    "46" REAL,
    "47" REAL,
    "48" REAL,
    "49" REAL,
    "50" REAL,
    "51" REAL,
    "52" REAL,
    "53" REAL,
    "54" REAL,
    "55" REAL,
    "56" REAL,
    "57" REAL,
    "58" REAL,
    "59" REAL,
    "60" REAL,
    "61" REAL,
    "62" REAL,
    "63" REAL,
    "64" REAL,
    "65" REAL,
    "66" REAL,
    "67" REAL,
    "68" REAL,
    "69" REAL,
    "70" REAL,
    "71" REAL,
    "72" REAL,
    "73" REAL,
    "74" REAL,
    "75" REAL,
    "76" REAL,
    "77" REAL,
    "78" REAL,
    "79" REAL,
    "80" REAL,
    "81" REAL,
    "82" REAL,
    "83" REAL,
    "84" REAL,
    "85" REAL,
    "86" REAL,
    "87" REAL,
    "88" REAL,
    "89" REAL,
    "90" REAL,
    "91" REAL,
    "92" REAL,
    "93" REAL,
    "94" REAL,
    "95" REAL,
    "96" REAL,
    "97" REAL,
    "98" REAL,
    "99" REAL,
    "100" REAL,
    "101" REAL,
    "102" REAL,
    "103" REAL,
    "104" REAL,
    "105" REAL,
    "106" REAL,
    "107" REAL,
    "108" REAL,
    "109" REAL,
    "110" REAL,
    "111" REAL,
    "112" REAL,
    "113" REAL,
    "114" REAL,
    "115" REAL,
    "116" REAL,
    "117" REAL,
    "118" REAL,
    "119" REAL,
    "120" REAL,
    "121" REAL,
    "122" REAL,
    "123" REAL,
    "124" REAL,
    "125" REAL,
    "126" REAL,
    "127" REAL,
    "128" REAL,
    "129" REAL,
    "130" REAL,
    "131" REAL,
    "132" REAL,
    "133" REAL,
    "134" REAL,
    "135" REAL,
    "136" REAL,
    "137" REAL,
    "138" REAL,
    "139" REAL,
    "140" REAL,
    "141" REAL,
    "142" REAL,
    "143" REAL,
    "144" REAL,
    "145" REAL,
    "146" REAL,
    "147" REAL,
    "148" REAL,
    "149" REAL,
    "150" REAL,
    "151" REAL,
    "152" REAL,
    "153" REAL,
    "154" REAL,
    "155" REAL,
    "156" REAL,
    "157" REAL,
    "158" REAL,
    "159" REAL,
    "160" REAL,
    "161" REAL,
    "162" REAL,
    "163" REAL,
    "164" REAL,
    "165" REAL,
    "166" REAL,
    "167" REAL,
    "168" REAL,
    FOREIGN KEY ("ID_Stromverbraucher") REFERENCES "Tab_Stromverbraucher" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_Stromverbrauchertyp_STAMM" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Typname" TEXT,
    "Beschreibung" TEXT,
    "1" REAL,
    "2" REAL,
    "3" REAL,
    "4" REAL,
    "5" REAL,
    "6" REAL,
    "7" REAL,
    "8" REAL,
    "9" REAL,
    "10" REAL,
    "11" REAL,
    "12" REAL,
    "13" REAL,
    "14" REAL,
    "15" REAL,
    "16" REAL,
    "17" REAL,
    "18" REAL,
    "19" REAL,
    "20" REAL,
    "21" REAL,
    "22" REAL,
    "23" REAL,
    "24" REAL,
    "25" REAL,
    "26" REAL,
    "27" REAL,
    "28" REAL,
    "29" REAL,
    "30" REAL,
    "31" REAL,
    "32" REAL,
    "33" REAL,
    "34" REAL,
    "35" REAL,
    "36" REAL,
    "37" REAL,
    "38" REAL,
    "39" REAL,
    "40" REAL,
    "41" REAL,
    "42" REAL,
    "43" REAL,
    "44" REAL,
    "45" REAL,
    "46" REAL,
    "47" REAL,
    "48" REAL,
    "49" REAL,
    "50" REAL,
    "51" REAL,
    "52" REAL,
    "53" REAL,
    "54" REAL,
    "55" REAL,
    "56" REAL,
    "57" REAL,
    "58" REAL,
    "59" REAL,
    "60" REAL,
    "61" REAL,
    "62" REAL,
    "63" REAL,
    "64" REAL,
    "65" REAL,
    "66" REAL,
    "67" REAL,
    "68" REAL,
    "69" REAL,
    "70" REAL,
    "71" REAL,
    "72" REAL,
    "73" REAL,
    "74" REAL,
    "75" REAL,
    "76" REAL,
    "77" REAL,
    "78" REAL,
    "79" REAL,
    "80" REAL,
    "81" REAL,
    "82" REAL,
    "83" REAL,
    "84" REAL,
    "85" REAL,
    "86" REAL,
    "87" REAL,
    "88" REAL,
    "89" REAL,
    "90" REAL,
    "91" REAL,
    "92" REAL,
    "93" REAL,
    "94" REAL,
    "95" REAL,
    "96" REAL,
    "97" REAL,
    "98" REAL,
    "99" REAL,
    "100" REAL,
    "101" REAL,
    "102" REAL,
    "103" REAL,
    "104" REAL,
    "105" REAL,
    "106" REAL,
    "107" REAL,
    "108" REAL,
    "109" REAL,
    "110" REAL,
    "111" REAL,
    "112" REAL,
    "113" REAL,
    "114" REAL,
    "115" REAL,
    "116" REAL,
    "117" REAL,
    "118" REAL,
    "119" REAL,
    "120" REAL,
    "121" REAL,
    "122" REAL,
    "123" REAL,
    "124" REAL,
    "125" REAL,
    "126" REAL,
    "127" REAL,
    "128" REAL,
    "129" REAL,
    "130" REAL,
    "131" REAL,
    "132" REAL,
    "133" REAL,
    "134" REAL,
    "135" REAL,
    "136" REAL,
    "137" REAL,
    "138" REAL,
    "139" REAL,
    "140" REAL,
    "141" REAL,
    "142" REAL,
    "143" REAL,
    "144" REAL,
    "145" REAL,
    "146" REAL,
    "147" REAL,
    "148" REAL,
    "149" REAL,
    "150" REAL,
    "151" REAL,
    "152" REAL,
    "153" REAL,
    "154" REAL,
    "155" REAL,
    "156" REAL,
    "157" REAL,
    "158" REAL,
    "159" REAL,
    "160" REAL,
    "161" REAL,
    "162" REAL,
    "163" REAL,
    "164" REAL,
    "165" REAL,
    "166" REAL,
    "167" REAL,
    "168" REAL,
    "ReadOnly" INTEGER NOT NULL DEFAULT 0 CHECK ("ReadOnly" IN (0,1))
) STRICT;

CREATE TABLE "Tab_Typ_Energieanlagen" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Bezeichner" TEXT NOT NULL
) STRICT;

CREATE TABLE "Tab_Variante" (
    "ID" INTEGER PRIMARY KEY,
    "ID_Projekt" INTEGER,
    "ID_ProjektRef" INTEGER,
    "Variantenname" TEXT
) STRICT;

CREATE TABLE "Tab_Waermebedarf" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Projekt" INTEGER DEFAULT 0,
    "Bezeichner" TEXT,
    "ReadOnly" INTEGER NOT NULL DEFAULT 0 CHECK ("ReadOnly" IN (0,1))
) STRICT;

CREATE TABLE "Tab_Waermebedarf_STAMM" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Bezeichner" TEXT,
    "ReadOnly" INTEGER NOT NULL DEFAULT 0 CHECK ("ReadOnly" IN (0,1))
) STRICT;

CREATE TABLE "Tab_WaermebedarfDaten" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Ganglinie" INTEGER NOT NULL,
    "Wert" REAL,
    FOREIGN KEY ("ID_Ganglinie") REFERENCES "Tab_Waermebedarf" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_WaermebedarfDaten_STAMM" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Ganglinie" INTEGER,
    "Wert" REAL,
    "ReadOnly" INTEGER NOT NULL DEFAULT 0 CHECK ("ReadOnly" IN (0,1)),
    FOREIGN KEY ("ID_Ganglinie") REFERENCES "Tab_Waermebedarf_STAMM" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Tab_WP" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Bezeichner" TEXT NOT NULL,
    "ID_Projekt" INTEGER,
    "Firma" TEXT,
    "Beschreibung" TEXT,
    "Typ" TEXT,
    "Baujahr" INTEGER,
    "Aufstellung" TEXT,
    "Nennleistung" INTEGER,
    "maxPtherm" INTEGER,
    "Heizung" INTEGER,
    "Regelung" TEXT,
    "Modulkosten" INTEGER,
    "Laenge" INTEGER,
    "Breite" INTEGER,
    "Hoehe" INTEGER,
    "Gewicht" INTEGER,
    "Raum" INTEGER,
    "Kuehlleistung" REAL,
    "Bauart" TEXT
) STRICT;

CREATE TABLE "Tab_WP_STAMM" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Bezeichner" TEXT NOT NULL,
    "Firma" TEXT,
    "Beschreibung" TEXT,
    "Typ" TEXT,
    "Baujahr" INTEGER DEFAULT 0,
    "Aufstellung" TEXT,
    "Nennleistung" INTEGER DEFAULT 0,
    "maxPtherm" INTEGER DEFAULT 0,
    "Heizung" INTEGER DEFAULT 0,
    "Regelung" TEXT,
    "Modulkosten" INTEGER DEFAULT 0,
    "Laenge" INTEGER DEFAULT 0,
    "Breite" INTEGER DEFAULT 0,
    "Hoehe" INTEGER DEFAULT 0,
    "Gewicht" INTEGER DEFAULT 0,
    "Raum" INTEGER DEFAULT 0,
    "Kuehlleistung" REAL DEFAULT 0,
    "Bauart" TEXT,
    "ReadOnly" INTEGER NOT NULL DEFAULT 0 CHECK ("ReadOnly" IN (0,1))
) STRICT;

CREATE TABLE "Z_AnlagePufferVerbund" (
    "ID" INTEGER PRIMARY KEY,
    "ID_Anlage" INTEGER,
    "ID_Puffer" INTEGER,
    "ID_Senke" INTEGER,
    FOREIGN KEY ("ID_Anlage") REFERENCES "Tab_Energieanlagen" ("ID") ON DELETE CASCADE,
    FOREIGN KEY ("ID_Puffer") REFERENCES "Tab_Pufferspeicher" ("ID")
) STRICT;

CREATE TABLE "Z_AnlageSenke" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Anlage" INTEGER NOT NULL,
    "Rang" INTEGER NOT NULL,
    "Ziel" TEXT CHECK (length("Ziel") <= 50),
    "Bedarfsart" TEXT CHECK (length("Bedarfsart") <= 50),
    "ID_Puffer" INTEGER,
    "Ladeprio" INTEGER,
    "Ladeprio_PV" INTEGER,
    "Ladegrenze" REAL,
    "Anschlusshoehe" REAL,
    FOREIGN KEY ("ID_Anlage") REFERENCES "Tab_Energieanlagen" ("ID") ON DELETE CASCADE,
    FOREIGN KEY ("ID_Puffer") REFERENCES "Tab_Pufferspeicher" ("ID")
) STRICT;

CREATE TABLE "Z_Projekt_Brauchwasser" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Projekt" INTEGER NOT NULL,
    "ID_Brauchwasser" INTEGER NOT NULL DEFAULT 0,
    "Bezeichner" TEXT,
    "Summe" REAL DEFAULT 0,
    FOREIGN KEY ("ID_Brauchwasser") REFERENCES "Tab_Brauchwasser" ("ID") ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY ("ID_Projekt") REFERENCES "Tab_Projekt" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Z_Projekt_Prozesswaerme" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Projekt" INTEGER NOT NULL,
    "ID_Prozesswaerme" INTEGER NOT NULL DEFAULT 0,
    "Bezeichner" TEXT,
    "Summe" REAL DEFAULT 0,
    FOREIGN KEY ("ID_Projekt") REFERENCES "Tab_Projekt" ("ID") ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY ("ID_Prozesswaerme") REFERENCES "Tab_Prozesswaerme" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Z_Projekt_Stromverbraucher" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Projekt" INTEGER NOT NULL,
    "ID_Stromverbraucher" INTEGER NOT NULL,
    "Bezeichner" TEXT,
    "Summe" REAL DEFAULT 0,
    FOREIGN KEY ("ID_Projekt") REFERENCES "Tab_Projekt" ("ID") ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY ("ID_Stromverbraucher") REFERENCES "Tab_Stromverbraucher" ("ID") ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY ("ID_Stromverbraucher") REFERENCES "Tab_Stromverbraucher" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Z_ProjektGebaeude" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Projekt" INTEGER NOT NULL,
    "Wohnflaeche_Waermebedarf" REAL,
    "Einheit_Waermebedarf_Wohnflaeche" TEXT,
    "Jahresnutzungsgrad" REAL,
    "dezWarmwasserbereitung" INTEGER NOT NULL DEFAULT 0 CHECK ("dezWarmwasserbereitung" IN (0,1)),
    FOREIGN KEY ("ID_Projekt") REFERENCES "Tab_Projekt" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Z_ProjektPufferSp" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Projekt" INTEGER NOT NULL DEFAULT 0,
    "ID_Pufferspeicher" INTEGER NOT NULL DEFAULT 0,
    "Pufferspeicher" TEXT NOT NULL,
    "Erzeuger" TEXT,
    "Vorlauf" INTEGER DEFAULT 0,
    "Ruecklauf" INTEGER DEFAULT 0,
    "Prioritaet" INTEGER DEFAULT 0,
    "Schwelle_Ein" REAL,
    "Schwelle_Aus" REAL,
    FOREIGN KEY ("ID_Projekt") REFERENCES "Tab_Projekt" ("ID") ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY ("ID_Pufferspeicher") REFERENCES "Tab_Pufferspeicher" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Z_ProjektSolarganglinie" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Projekt" INTEGER NOT NULL,
    "ID_Ganglinie" INTEGER NOT NULL DEFAULT 0,
    "Bezeichner" TEXT,
    FOREIGN KEY ("ID_Projekt") REFERENCES "Tab_Projekt" ("ID") ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY ("ID_Ganglinie") REFERENCES "Tab_Solarganglinie" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Z_ProjektStromganglinie" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Projekt" INTEGER NOT NULL,
    "ID_Ganglinie" INTEGER NOT NULL DEFAULT 0,
    "Bezeichner" TEXT,
    FOREIGN KEY ("ID_Projekt") REFERENCES "Tab_Projekt" ("ID") ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY ("ID_Ganglinie") REFERENCES "Tab_Stromganglinie" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

CREATE TABLE "Z_ProjektWaermebedarf" (
    "ID_Z" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_Projekt" INTEGER NOT NULL,
    "ID_Ganglinie" INTEGER NOT NULL,
    "Bezeichner" TEXT,
    "Kanal" TEXT CHECK (length("Kanal") <= 50),
    FOREIGN KEY ("ID_Projekt") REFERENCES "Tab_Projekt" ("ID") ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY ("ID_Ganglinie") REFERENCES "Tab_Waermebedarf" ("ID") ON UPDATE CASCADE ON DELETE CASCADE
) STRICT;

PRAGMA foreign_keys = ON;
