// <auto-generated />
// Erzeugt von sql/tools/Erzeuge-Schema.ps1, Quellenstand 2026-09-01 15:16
// Quelle: Kenndaten.accdb (Schemastand 61)
// NICHT VON HAND AENDERN - neu erzeugen.
//
// Zweck (Implementierungskonzept 2.4): zentrale Typangleichung im neuen GetDataTable.
// SQLite kennt weder Boolean noch Datum; beide kommen als INTEGER bzw. TEXT zurueck.
// Spaltennamen, die in einer Tabelle Boolean/Datum und in einer anderen einen anderen
// Typ tragen, sind hier BEWUSST NICHT enthalten (siehe S2-Protokoll, Kurationspunkte):
//   Boolean mehrdeutig: Heizstab
//   Datum mehrdeutig  : -

using System;
using System.Collections.Generic;

namespace WindowsFormsApplication1.Allgemein
{
    internal static class SchemaTypKatalog
    {
        /// <summary>Access-Boolean-Spalten (SQLite: INTEGER 0/1).</summary>
        internal static readonly HashSet<string> BoolSpalten =
            new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "Aktiv",
            "Anteil_CO2_Aktiv",
            "Anteil_Energiesteuer_Aktiv",
            "Anteil_Netzentgelt_Aktiv",
            "Anteil_Vertrieb_Aktiv",
            "Aufschlaege_Anwenden",
            "Aufschlag_Anwenden",
            "Aufschlag_Konzession_Aktiv",
            "Aufschlag_Netzentgelt_Aktiv",
            "Aufschlag_Stromsteuer_Aktiv",
            "Aufschlag_Umlagen_Aktiv",
            "Aufschlag_Vertrieb_Aktiv",
            "BHKW_Stromgefuehrt",
            "BHKW_Ueberschuss_Zulaessig",
            "BezugAusPreisreihe",
            "Bivalenter_Betrieb",
            "Brennwert",
            "Extrapolation_erlaubt",
            "Hocheffizienz_Nachweis",
            "IsMainComponent",
            "IstErloes",
            "IstPflicht",
            "IstStamm",
            "IstStandard",
            "KWKG_Pauschalmodus",
            "Kaskade_Zweikanalig",
            "Kompatibilitaetsmodus",
            "Netzentladung",
            "Nutzung_Brauchwasser",
            "Nutzung_Heizung",
            "Nutzung_Prozess",
            "PV_Zulaessig",
            "Par51a_Kompensieren",
            "Raeumlicher_Zusammenhang",
            "ReadOnly",
            "Sim_BHKW",
            "Sim_Energiebedarf",
            "Sim_Heizkessel",
            "Sim_PV",
            "Sim_Solarthermie",
            "Sim_Stromspeicher",
            "Sim_Waermepumpe",
            "Sperrung",
            "Veraenderbar",
            "WE",
            "WP_Heizstab",
            "WQ_Unbegrenzt",
            "aktiv",
            "ausgewaehlt",
            "dezWarmwasserbereitung",
            "has_density",
            "has_hi",
            "has_hs",
            "has_powerprice",
            "is_active",
            "ist_aktiv",
            "ist_auslieferung",
            "ist_co2e",
            "ist_pflicht",
            "rendeMix",
            "user_edited",
        };

        /// <summary>Access-Datumsspalten (SQLite: TEXT 'YYYY-MM-DD HH:MM:SS').</summary>
        internal static readonly HashSet<string> DatumSpalten =
            new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "Aenderungsdatum",
            "Erstelldatum",
            "GeaendertAm",
            "Inbetriebnahme",
            "KWKG_Inbetriebnahme",
            "KWKG_Stichtag",
            "Tarif_GueltigAb",
            "Zeitstempel",
            "gueltig_ab",
            "valid_from",
            "valid_to",
        };
    }
}
